### ISSUE TITLE
Change property graphing lib

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#162]
We need to change the property graphing library to one that allows a fluid sparkline addition and that allows a min and max alarm values to be displayed as boundaries on the graph so you can see how close to the boundaries the property is operating.

@sweety-wo Some possible options to evaluate:
http://www.chartjs.org/
https://developers.google.com/chart/
http://gionkunz.github.io/chartist-js/
http://epochjs.github.io/epoch/

**Comment by sweety-wo** [comment]
I have implemented used 'https://developers.google.com/chart/' library for display line chart with max and min alert on incident detail page at right side.

see Image:
![google_line_chart](https://cloud.githubusercontent.com/assets/14175105/16045153/da39fbf8-3264-11e6-973b-0cd171d43b73.png)

@tarkal Is it OK?
If, It is OK then tell me.
So,  I will implement it in property modal.

**Comment by tarkal** [comment]
I like it.

**Comment by sweety-wo** [comment]
Closed #162; Implement Google chart at Property Modal and remove spark line graph code.

Also Implement Google chart at incident detail page property tab and remove spark line graph code and display spark line graph in property table as it is.
