### ISSUE TITLE
Network overview node access

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#163]
The network overview chart needs to have the possibility of accessing a node in the property manager directly.

Clicking the node on the network graph currently filters in on that node. One possible solution is that we add a right click option menu to 'view node'. Not sure if its better to have the 'view node' as the default behaviour or the zoom effect. @sweety-wo what do you think, other alternative solutions?

**Comment by sweety-wo** [comment]
Add a right click option menu to 'View'.
when you click on 'view' option it redirect on node property page.

See following image 'view' option show on right click. 

![image](https://cloud.githubusercontent.com/assets/14175105/14909405/9afc3ec0-0e00-11e6-8adb-8c1c4828ef8a.png)
