### ISSUE TITLE
@ignore extra takes no values

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#186]
The reserved `@ignore` for extra data does not take any values. The validator should allow the creation without the need for a value to be specified.

**Comment by sweety-wo** [comment]
I have allowed creation and updation when extra data key is `@ignore`.
![screenshot-localhost 3000 2016-05-03 16-01-04](https://cloud.githubusercontent.com/assets/14175105/14980889/13a43670-1149-11e6-9e99-3edc36f93e7d.png)
