### ISSUE TITLE
Incomparable browser messgae

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#189]
A user tried to load the GUI in an old version of Internet explorer and the page simply did not load. 

We need to add a message for incompatible browsers instead of just not loading.

**Comment by sweety-wo** [comment]
I have checked it in older then IE 10 browsers. The message is  already displayed.

I have added style to it for display clean.

![image](https://cloud.githubusercontent.com/assets/14175105/14981522/672bb0e4-114d-11e6-8706-0f5a4aafe5f7.png)
