### ISSUE TITLE
Property boolean history color

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#191]
The property boolean history should avoid using red and green to represent true and false. The problem is that `True` and `False` values do not reflect whether the value is expected to be `True` or `False`. 

I think we should use two shades of blue to represent the values.

**Comment by sweety-wo** [comment]
You means replace two blue color `(#0000ff` and `#0066ff)`instead of red and green color?

**Comment by tarkal** [comment]
Yes, The problem with green and red is they indicate good and bad. But some values are good when they are off and bad when they are on. So red is misleading.

**Comment by sweety-wo** [comment]
Okay, I have use `#5b7be3` for true and `#6495ed` for false.

![image](https://cloud.githubusercontent.com/assets/14175105/14982165/17631a0c-1152-11e6-8a2d-fdd83e618f89.png)
