### ISSUE TITLE
Generic Incident Search does not work

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#192]
The generic Incident search bar does not filter to the properties properly. If I type in `Temp` I would expect it to perform a filter but the table does not seem to be updated properly and the filter is not applied.

**Comment by sweety-wo** [comment]
I have completed generic incident search bar but there is an issue with API. 

![image](https://cloud.githubusercontent.com/assets/14175105/14916722/dbfe0b1e-0e38-11e6-9451-66a27db7bb59.png)

You can see above incidents table have **`Tx In Power #1`** record but when I type **`Tx In Power #1`** and send request with **`any:=Tx In Power #1`** param then API return blank array.

![image](https://cloud.githubusercontent.com/assets/14175105/14916734/f08fade4-0e38-11e6-86d3-d4c4d54dcdc4.png)

![image](https://cloud.githubusercontent.com/assets/14175105/14916741/fa18a6d6-0e38-11e6-8f98-d9d8e4e32a5b.png)


I have committed this changes please check it. If any issue then let me know.

**Comment by tarkal** [comment]
@sweety-wo As per the API docs the single `=` means `equals`. The `any` query parameter is designed to perform matches to any of the permitted search fields. But this means that the value must be an EXACTLY match to the field for a value to be considered a match and returned.

There is a much better option for this use case that uses `==` and this is the equivalent of `like`. This does not require exact matches. So instead of using `any=Some query` use `any==Some query`. I checked this and it seems to work fine via the API.
