### ISSUE TITLE
Network Diagram

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#193]
We should remove Projects from the Network diagram centre ring. The centre ring should be the Sector. However there should be a search bar at the top that allows you to filter by project.

**Comment by tarkal** [comment]
Lets also have a revamp…

![screen shot 2016-04-30 at 15 28 16](https://cloud.githubusercontent.com/assets/7042623/14938729/a09456ac-0eea-11e6-92c9-eab85a98bef0.png)

@sweety-wo what do you think?

**Comment by sweety-wo** [comment]
I think it's good UI.

There are following question regarding UI : 

- What about breadcrumb?  
- At right side initial level display list of property or not?
- For display properties use context menu or not?  because right now using context menu redirect on  detail page and when click on sunbrust zoom in/out.
- For project search bar,  use multipal tag input to search multipal projects or a single project search?
- After search project using project search bar to filter graph then network graph then project display in center of ring?

**Comment by tarkal** [comment]
* What about breadcrumb?
Yes keep the breadcrumb, however currently the breadcrumb is only displayed when the mouse is hovering over a node. It should be permanently display the breadcrumb of the current location but override the path with the hover.

* At right side initial level display list of property or not?
No, only display when a node is selected.

* For display properties use context menu or not? because right now using context menu redirect on detail page and when click on sunburst zoom in/out.
Yes keep the context its good, also clicking on the property should display it in a modal.

* For project search bar, use multiple tag input to search multiple projects or a single project search?
Multiple

* After search project using project search bar to filter network graph then project display in centre of ring like current network graph?
No, the filter should just filter the sectors to only display the sectors in a filtered project.

**Comment by sweety-wo** [comment]
I have question about "more properties" and "see incident" link.

- Should I display all properties of selected node  or only display "21" properties?

Currently, I have display all properties of selected node 
See Image:
![screenshot-localhost 3000 2016-05-05 16-22-23](https://cloud.githubusercontent.com/assets/14175105/15041975/b218c0ba-12dd-11e6-9544-f32f2f6ee4fb.png)

- If init display "21" properties of selected node like display in above your image then What should I do on 'more properties' link?
Redirect to node property page or display next '21' properties?

- What should I do on "see incident" link?

**Comment by tarkal** [comment]
I think we should display only the first 20 properties and always put the unhealthy ones at the top and hide the rest. The display more should only be there if there are more than 20 and it should just expand / uncover the rest.

The view incidents should open the incident page with a filter applied to that node.
