### ISSUE TITLE
Incident reports click through

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#195]
On the incidents report page it should be possible to click on respective values like 'Started', 'Ended', 'Max state transitions', 'Min state transitions', 'Max state transitions' etc. and actually see the incident that was responsible.

The table should also provide click through like the main incidents table to be able to see the specific incident.

**Comment by sweety-wo** [comment]
On the incidents report page it should be possible to click on respective values like 'Started', 'Ended',etc.. means
Suppose, there is 5 incident count for 'Ended"
When I click on 'Ended" then display 5 incident in incident table

Also Need to count 'Max State Transitions', 'Min State Transitions', 'Most common incidents', Most common nodes etc... for 5 "Ended" incidents.

Is it OK?

**Comment by sweety-wo** [comment]
Done.
![filter incident report](https://cloud.githubusercontent.com/assets/14175105/18671873/6258b25e-7f63-11e6-81a1-0c7d60622bba.gif)
