### ISSUE TITLE
Incident count

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#201]
If you are signed into the system with an account that has access to incidents and you then sign out and log into another account that does not have access to those incidents, you still see the same number of incidents in the count. 

When you go to the incidents they are not displayed (correct) but the count suggests there should be incidents.

**Comment by sweety-wo** [comment]
I have checked it. You are correct.
I have display 'incident count' from API **'Response Headers > Link(rel="final")**':

I think API wrong return response
Response blank array [] but 
Response Headers > Link return 21 pages in rel="final"
Response Headers > Link:
< http://54.67.43.161:8080/api/incidents?page=2&perPage=1 >; rel="next",
< http://54.67.43.161:8080/api/incidents?page=1&perPage=1 >; rel="prev",
< http://54.67.43.161:8080/api/incidents?page=1&perPage=1 >; rel="first",
< http://54.67.43.161:8080/api/incidents?page=21&perPage=1 >; rel="last",
**< http://54.67.43.161:8080/api/incidents?page=21&perPage=1 >; rel="final"**

**See following response image:**
![image](https://cloud.githubusercontent.com/assets/14175105/14910090/25c0e978-0e08-11e6-87d8-988a862f95a2.png)

![image](https://cloud.githubusercontent.com/assets/14175105/14910110/4c64c9be-0e08-11e6-8a19-84f5c85db903.png)

**Comment by tarkal** [comment]
Ok this has been referenced as a core issue here: 

https://github.com/ff36/halo-core/issues/77
