### ISSUE TITLE
Authentication Username watermark.

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#202]
Please take a look at this issue:
https://github.com/ff36/halo-core/issues/74

**Comment by sweety-wo** [comment]
I have replaced placeholder as "Email" instead of "Username".

![screenshot-localhost 3000 2016-05-02 13-56-21](https://cloud.githubusercontent.com/assets/14175105/14950324/73234f7c-106e-11e6-987d-a5078f02f1b9.png)
