### ISSUE TITLE
"Include Silenced" logic

### ISSUE THREAD

**Issue by jimwitkin** [ff36/halo-gui#204]
In screens where the "Include silenced" option is available, the toggle should say "Yes/No" not "On/Off" as it is currently implemented.  Yes/No is more logical 

![image](https://cloud.githubusercontent.com/assets/18722397/14896168/a72f8110-0d39-11e6-8577-293362d9687d.png)

**Comment by sweety-wo** [comment]
fixed #204

I have change switch content

![yes](https://cloud.githubusercontent.com/assets/14175105/14949757/1f52780e-106a-11e6-9fda-895b958436b2.png)

![no](https://cloud.githubusercontent.com/assets/14175105/14949762/27b3f554-106a-11e6-84c2-ee69e34d71e8.png)
