### ISSUE TITLE
Floating Navigation Bar

### ISSUE THREAD

**Issue by jimwitkin** [ff36/halo-gui#206]
It would be nice if the Navigation Bar would stay in place (float) on scrolling screens. Right now if I'm working on a screen with a scroll capability, when I scroll down, the Navigation Bar (shown in attached graphic) scrolls off screen. It would be useful if this Nav Bar stayed in place on the screen regardless of where I am scrolling up or down.  

![image](https://cloud.githubusercontent.com/assets/18722397/14896248/f9558084-0d39-11e6-9e36-c4c250c2c72c.png)

**Comment by sweety-wo** [comment]
I have implemented fixed menu when navigation menu is expanded and applied scroll on it

![fixed_menu](https://cloud.githubusercontent.com/assets/14175105/16044149/d05419f6-3260-11e6-8024-94b47cde509d.png)

But when navigation menu is collapsed and if i set position fixed and apply scroll then sub-menu can't display on parent menu hover so I have't added fixed position for navigation menu when collapsed.

Still i will try to find solution to overcome this. but there is less possibility of doing this. also same issue is there with theme we are using but they are just hiding it and in same case we want to display sub-menu.
