### ISSUE TITLE
Non Admin cant create subscription

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#207]
None admin users cant create subscriptions at the moment.

**Comment by sweety-wo** [comment]
So, Should I add 'Subscription' permission that can be access by admin only like 'Manage Halo' ?

**Comment by tarkal** [comment]
@sweety-wo Sorry what I mean is that everybody SHOULD be able to create subscriptions but non-administrator accounts currently cannot. I am not sure if this is a GUI problem or a core problem. Please could you test it and let me know.

**Comment by sweety-wo** [comment]
I have check it..

I think It's **issue on live**.
It's working **fine** in **local**. Subscriptions created by both user "**Admin**" and "**Non-Admin**".
But, on live (http://54.67.43.161) Subscriptions not created by "**Non-Admin**" user. its given a **404 Not Found** error.

See Following images
**LOCAL : Admin User**
![image](https://cloud.githubusercontent.com/assets/14175105/14948231/b3b80446-105b-11e6-9fcb-7efea5c618d4.png)

**LOCAL : Non-admin User**
![image](https://cloud.githubusercontent.com/assets/14175105/14948117/79f725c6-105a-11e6-98e8-b00eb772ee86.png)

**LIVE: Non-admin User**
![image](https://cloud.githubusercontent.com/assets/14175105/14948171/0b566bbc-105b-11e6-94cf-c6c13683a6ff.png)

**Comment by tarkal** [comment]
No, This is a core bug so I will fix it.
