### ISSUE TITLE
The GMap plugin does not load the map

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#208]
The GMap plugin map is not loading in the latest version.

![screen shot 2016-04-28 at 17 04 16](https://cloud.githubusercontent.com/assets/7042623/14904126/48fe0a10-0d63-11e6-8366-e1f9c8a03a0b.png)

**Comment by sweety-wo** [comment]
I think it take time for load map because of API response.
So, we need to display loader in plugin

**Comment by tarkal** [comment]
@sweety-wo The loader looks great but the problem was actually an error from the API not a timeout. The plugin was querying a sector that was corrupt and the API was returning a 404 error that caused the plugin not load the map.

I have fixed the error in the API but this issue should be solved in the plugin itself. I have opened an adjacent issue in the Gmap plugin repo https://github.com/ff36/halo-plugin-gmap/issues/5
