### ISSUE TITLE
Remove nav sandwich

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#214]
- Remove the nav sandwich.
- Move the user far left
- Add collapse / expand function from sandwich to logo

![screen shot 2016-04-30 at 15 17 44](https://cloud.githubusercontent.com/assets/7042623/14938643/69bf73d0-0ee7-11e6-8508-cc947d118335.png)

**Comment by sweety-wo** [comment]
I have remove nav sandwich.
Moved the user far left
Added collapse / expand function from sandwich to logo

See following images:
**Collapse**
![screenshot-localhost 3000 2016-05-03 14-12-56](https://cloud.githubusercontent.com/assets/14175105/14978472/aecd02ea-1139-11e6-82d2-c6992b845e18.png)

**Expand**
![screenshot-localhost 3000 2016-05-03 14-14-51](https://cloud.githubusercontent.com/assets/14175105/14978484/beb435e8-1139-11e6-87f2-1c09c2f5eec9.png)
