### ISSUE TITLE
Single IP specification

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#222]
When a GUI is updated it currently pulls the latest code from Github and the does a `gulp build`. During the build the IP address specified in `src/app/components/halosdk/Configuration.js`:

```
'use strict';
angular.module('HaloSDK',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "http://localhost:8080/api",
        ...
    };
});
```
This then gets compressed into multiple js files. This is fine for systems that have outside access and the process can be automated. However, this is really annoying for systems that have to be manually updated because you have to know the IP address BEFORE you build the GUI and upload it to the system. 

@sweety-wo Is there a way to set that value in 1 place in the dist AFTER the build and have it dynamically injected into the multiple compressed js?

**Comment by sweety-wo** [comment]
I have created **host.js** file to set IP value in 1 place in the dist AFTER the build. 
Also, **host.js** file copy from **/src** folder after gulp build done and overwrite existing one.

**Comment by tarkal** [comment]
Great. So when you do `gulp build` a file called `host.js` is created in the root `dist` directory. Inside `host.js` you can set the value of the equivalent `BASEURI` at runtime?

**Comment by sweety-wo** [comment]
yes...

I have create host.js with one variable 'HOST_URL' 
and this variable assign to BASEURI : HOST_URL in  halosdk ->Configuration.js

```
'use strict';
angular.module('HaloSDK',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : HOST_URL,
        ...
    };
});
```
