### ISSUE TITLE
Network diagram breadcrumb

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#226]
The network manager breadcrumb should stay on when a node is selected or the properties are being displayed.

**Comment by sweety-wo** [comment]
Breadcrumb working on mouse hover. so if you want to show stay path for selected property then we need to stop breadcrumb update on hover. 

So I have display selected path show on right side.  see the image

![screenshot- domain date time](https://cloud.githubusercontent.com/assets/14175105/15884130/c741add2-2d6b-11e6-8e47-a3f5ba13062a.png)


Should I stop breadcrumb update on mouse hover and remove path from right side?
