### ISSUE TITLE
Network diagram centre

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#227]
Lets remove the logo from the centre of the network diagram and replace it with the number of incidents in the sun dial.

**Comment by sweety-wo** [comment]
Display number of incident in center of network diagram when hover on node and sector of network diagram,

![network incident](https://cloud.githubusercontent.com/assets/14175105/15112693/79b91fa2-160d-11e6-9726-a26c2fd6b7d0.png)

**Comment by tarkal** [comment]
Doesn't look quite so good my end...

![screen shot 2016-05-09 at 15 51 18](https://cloud.githubusercontent.com/assets/7042623/15117201/c97b325c-1606-11e6-9c7d-f1efa368292d.png)

**Comment by sweety-wo** [comment]
Count display in center of burst and property status show as round shape in all screen

![network incident](https://cloud.githubusercontent.com/assets/14175105/15136538/fc8f6bce-169f-11e6-9980-e05dbe2a9aec.png)

**Comment by tarkal** [comment]
The count should be constantly there.
