### ISSUE TITLE
Network property edit

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#233]
I found the following problems with the network property edit modal:

![screen shot 2016-05-12 at 09 41 49](https://cloud.githubusercontent.com/assets/7042623/15208214/97ec05a6-182a-11e6-9ea3-7f5dae40807c.png)

**Comment by sweety-wo** [comment]
Editing string values does not display the edit input box when property has readOnly false.

Okay, Done it.

Now Editing string values does display the edit input box when property has readOnly false.
![screenshot-localhost 3000 2016-05-12 14-47-13](https://cloud.githubusercontent.com/assets/14175105/15209892/4205c038-1851-11e6-95eb-13ede4ecf615.png)
