### ISSUE TITLE
Sunburst spacing

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#234]
The space between the sunburst and the breadcrumb is too big.  On a small screen it should really be more compact.

![screen shot 2016-05-12 at 09 42 29](https://cloud.githubusercontent.com/assets/7042623/15208269/f67079f4-182a-11e6-9fa2-a13600d4e3ed.png)

**Comment by sweety-wo** [comment]
I have reduce height of sunburst graph for remove space between the sunburst and the breadcrumb.

see following image for (1280 x 800 resolution screen)

![network](https://cloud.githubusercontent.com/assets/14175105/15209625/c8e8a234-184f-11e6-88fa-6b3c66977f30.png)
