### ISSUE TITLE
Can't create subscriptions

### ISSUE THREAD

**Issue by jimwitkin** [ff36/halo-gui#236]
getting error message (see attached image) when trying to create subscriptions. tried topic #incident and #authentication. tried to dispatch to message using my halo email  

![image](https://cloud.githubusercontent.com/assets/18722397/15220184/73b1edfe-181b-11e6-8f14-46dffc977618.png)

**Comment by tarkal** [comment]
I think this is due to the same account corruption reported in your other other question as this does not happen on other systems or in our tests. I will investigate and report back.

**Comment by tarkal** [comment]
Resolved
