### ISSUE TITLE
Can't view sectors 

### ISSUE THREAD

**Issue by jimwitkin** [ff36/halo-gui#237]
Not able to view sector. when I hit the view icon, this message appears but nothing ever loads 

![image](https://cloud.githubusercontent.com/assets/18722397/15220436/6505ccca-181c-11e6-9fef-66a0da53ec99.png)

**Comment by tarkal** [comment]
This is a known error. Sometimes the loader gets caught on a loop and the page doesn't load. Just refresh the page.

**Comment by tarkal** [comment]
@sweety-wo It might be worth having a timeout - retry for this. Its not very common but it does happen on occasion that the loader never actually seems to load the data. What do you think?

**Comment by jimwitkin** [comment]
Nope, I couldn't get the Sector view to load no matter how many times I
refreshed the page. I even turned off my ad blocker

On Thu, May 12, 2016 at 10:06 AM, tarkal <notifications@github.com> wrote:

> This is a known error. Sometimes the loader gets caught on a loop and the
> page doesn't load. Just refresh the page.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ff36/halo-gui/issues/237#issuecomment-218821790>
>



-- 


<http://www.solid.com>

*Jim Witkin, SOLiD Technical Publications*
*T* 650 218 1872 *| E* jim.witkin@solid.com
*HQ:*   617 N MARY AVE *|* SUNNYVALE CA 94085
*MAIN:*  888.409.9997  *|*  www.SOLiD.com <http://www.solid.com/>

      * SOLiD BLOG   <http://solid.com/blog/>   TWITTER
<https://twitter.com/solidusa>*   *YOUTUBE  *
<http://www.youtube.com/channel/UCAGgwjhqh-4xUVigSeb4d3w/videos>   *LINKEDIN
* <http://www.linkedin.com/company/solid-technologies>

**Comment by sweety-wo** [comment]
@tarkal I think API goes to in pending. so maybe loader continue display.
I have removed loader and display **Welcome to "Sector"** message when API failed.

**Comment by tarkal** [comment]
@sweety-wo Actually on this occasion it seems to be a problem with @jimwitkin account. I don't know why its happening just yet but his account seems to be corrupted on demo hence why he cant generate subscriptions or view sectors. I will look at the logs and report.

That said the original point still stands. If the API goes into pending lets do a retry. Ill leave it up to you how many time to retry.

**Comment by tarkal** [comment]
@jimwitkin this should be fixed. The sector I shared with you was corrupted. I am continuing investigation into the origin of the corruption. You should now be able to access the demo sector in your account.

**Comment by jimwitkin** [comment]
All seems to be working now. thanks. Having an active sector to play with is really helpful
