### ISSUE TITLE
Change graphic

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#247]
The node trace on the node details page is currently using the graphics that are now reserved for the INF plugin. Instead it should use graphics that represent the current look and feel of the native node manager.

current:
![screen shot 2016-05-18 at 16 47 35](https://cloud.githubusercontent.com/assets/7042623/15385757/fccf8bfe-1da3-11e6-90f5-806fa27b403b.png)

**Comment by tarkal** [comment]
@sweety-wo The incidents page is still using this graphic:

![screen shot 2016-06-24 at 11 22 17](https://cloud.githubusercontent.com/assets/7042623/16334020/e29a3a3c-39fe-11e6-988f-3dc607c3be30.png)

**Comment by tarkal** [comment]
@sweety-wo This is still being used in 1.3.0-alpha

**Comment by sweety-wo** [comment]
I have Changed The incidents page Index UI

![changed_index_ui](https://cloud.githubusercontent.com/assets/14175105/16444253/d49efdb4-3dfa-11e6-86cd-31d11e8ac73d.png)
