### ISSUE TITLE
Can't use message dispatcher when creating subscriptions

### ISSUE THREAD

**Issue by jimwitkin** [ff36/halo-gui#252]
The option to be notified via Message (Dispatcher drop down menu) is no longer available when creating a subscription

![image](https://cloud.githubusercontent.com/assets/18722397/15403135/586e2f80-1dac-11e6-82b6-f96c5f4738d1.png)

**Comment by tarkal** [comment]
Sorry I removed it from the global as part of my tests. Check again, I added it to your project.

**Comment by jimwitkin** [comment]
Yep, messages are back but I'm getting the HTTP error message when I try to use the Message dispatcher 

![image](https://cloud.githubusercontent.com/assets/18722397/15403370/88ed101c-1dad-11e6-8af6-45d2aff5e4ec.png)

**Comment by tarkal** [comment]
Sorry, helps if I give you permission! Try now.

**Comment by jimwitkin** [comment]
Bingo. that works.

![image](https://cloud.githubusercontent.com/assets/18722397/15403542/526dfcf8-1dae-11e6-8c58-89d70a00b4a2.png)
