### ISSUE TITLE
Graphics on Dashboard not displaying correctly

### ISSUE THREAD

**Issue by jimwitkin** [ff36/halo-gui#253]
My screen zoom factor is at 100% but some of the Halo images on the dashboard aren't displaying correctly. See attached. The 100% pie is overlapping with some of the other graphics

![image](https://cloud.githubusercontent.com/assets/18722397/15403198/b63a3dd4-1dac-11e6-99aa-d42e55e3b583.png)

**Comment by tarkal** [comment]
Please can you provide your browser and os details.

**Comment by jimwitkin** [comment]
Using Windows 10 (god help me) and Chrome. If I change the zoom factor to 90%, the graphics display properly (or at least the way I think you intended). Attached screen image taken at 90% zoom

![image](https://cloud.githubusercontent.com/assets/18722397/15403462/e55abb24-1dad-11e6-8c62-2193b02c1051.png)

**Comment by tarkal** [comment]
Can you provide your screen resolution and chrome version.

**Comment by jimwitkin** [comment]
Chrome version in attached screen image.

![image](https://cloud.githubusercontent.com/assets/18722397/15403574/76f06818-1dae-11e6-8eca-288d2bb75c8e.png)

Screen resolution is 1680 x 1050

![image](https://cloud.githubusercontent.com/assets/18722397/15403613/b68394d2-1dae-11e6-85c1-8ae97f7b6afc.png)

**Comment by sweety-wo** [comment]
I have tested on browserstack with following configuration: 

- OS : Windows 10
- Resolution : 1680 X 1050
- Chrome version : 50

![screenshot from 2016-06-08 11 41 28](https://cloud.githubusercontent.com/assets/14175105/15884433/03fed630-2d6e-11e6-8b3d-f04829f6bcc6.png)

It's working fine for me. let me know if any issue.

**Comment by tarkal** [comment]
@jimwitkin Is this issue resolved for you?

**Comment by jimwitkin** [comment]
appears to be

**Comment by tarkal** [comment]
Thx
