### ISSUE TITLE
Global plugin icon

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#263]
Lets change the global plugin icon to `universal-access`:

http://fontawesome.io/icon/universal-access/

**Comment by sweety-wo** [comment]
I have changed global plugin icon to `universal-access` on plugin grid page
**Is it OK?**

![plugin-globle-icon](https://cloud.githubusercontent.com/assets/14175105/15641024/7dc0ee0a-265b-11e6-9094-2cec780fc60c.png)

**Comment by tarkal** [comment]
@sweety-wo Maybe a tiny bit smaller. What do you think?

**Comment by sweety-wo** [comment]
Yes... A tiny bit smaller is looking better...

![plugin-globle-icon](https://cloud.githubusercontent.com/assets/14175105/15642186/4a568158-2663-11e6-8a3a-fc06ba02718c.png)

**Comment by tarkal** [comment]
Spot on...
