### ISSUE TITLE
Implement dynamic header menu

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#270]
The API has a method `getHeaderMenu()`. It works in the same way as the navigation menu and allows plugins to dynamically create header icons. 

The default browser icons should occupy the normal positions (these are not modifiable). The dynamic ones should then be injected as shown:

![screen shot 2016-05-30 at 09 31 04](https://cloud.githubusercontent.com/assets/7042623/15646577/9fc05984-265e-11e6-9f16-ab15603c17b2.png)

Position 1 being the farthest right and working up incrementally to the left.

**Comment by sweety-wo** [comment]
I have bind `getHeaderMenu()` method response in top navigation bar.
**Currently click event is not bind, just display menu items**

See Image with dummy data:
![top_plugin_menus](https://cloud.githubusercontent.com/assets/14175105/15649825/0cdd2fd2-2692-11e6-8545-0a40f721e367.png)

**Comment by tarkal** [comment]
Thats great. based on our discussion earlier the click event bind is not critical as we are looking to modify this to include include functions.
