### ISSUE TITLE
Properties Filter and order table

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#277]
The properties table for both the network manager and the node manager should have a filter bar at the top to filter the properties in the table and should have table sorting to change the order by column.

This is only local as we have already loaded all the properties.

**Comment by tarkal** [comment]
Functionally this is great.

![screen shot 2016-06-04 at 16 06 33](https://cloud.githubusercontent.com/assets/7042623/15799982/63458e5c-2a6e-11e6-9b2f-b177ce061dd9.png)

However, aesthetically not so much! It needs to be in keeping with the rest of the app. 
* The table needs to go back to the same width as before.
* The search bar needs to be above the table.
* The search bar needs to be the full width of the table.
* No label before the search bar.
* A light grey watermark placeholder in the search bar with the word 'Search'.

![screen shot 2016-06-04 at 16 06 33](https://cloud.githubusercontent.com/assets/7042623/15800032/9ae5662e-2a6f-11e6-92f9-2a03021e0b86.png)

**Comment by sweety-wo** [comment]
I have changed search bar.

**See Image:**
![image](https://cloud.githubusercontent.com/assets/14175105/15922589/258b1542-2e46-11e6-8bf6-95894f0a0079.png)

**Comment by tarkal** [comment]
The sunburst completely stalls the site! Unfortunately I think the refresh function is shorter than the time it takes to complete the load. So when you request a nodes properties it takes way way too long and you can’t navigate away from the page either. Why is it taking so long to load? Incidents should just be a single API call -> getIncidents(hello, red, silent=false). This should give you ALL the incidents for ALL sectors. You can then filter clients side. Let me know your thoughts.
