### ISSUE TITLE
Subscription 'Use custom settings' hideExpression

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#294]
This issue was reported a while ago but I cant find it. The `hideExpression` used in the 'Use custom settings' toggle on the Subscription modal seems to behave erratically. Sometimes the expression is respected and other times its not.

As best as I can tell if the **Twilio Dispatcher** is selected as the first option when the modal opens the `hideExpression` is not respected:

![screen shot 2016-06-16 at 08 50 46](https://cloud.githubusercontent.com/assets/7042623/16107900/b033314e-339f-11e6-9601-5550047200a5.png)

However subsequent selections do seem to work:

![screen shot 2016-06-16 at 08 54 12](https://cloud.githubusercontent.com/assets/7042623/16107922/efcb8a0e-339f-11e6-96f6-61babf18285e.png)

It seems to be specific to the Twilio dispatcher but I cant be 100% sure.

**Comment by sweety-wo** [comment]
I have done following : 

- Subscription 'Use custom settings' hideExpression for both create and update subscription. 
- Save button disabled issue for invalidate form.

Please check it. if any issue then let me know.

**Comment by tarkal** [comment]
This is still not fixed in the latest pull.

**Comment by sweety-wo** [comment]
I have test in chrome and Firefox browser

**1.  Chrome** : (Version : Version 51.0.2704.84 m and OS Windows 7)

![sub_test](https://cloud.githubusercontent.com/assets/14175105/16141829/39bf1e18-347d-11e6-97e2-67dcbf85a984.gif)

**2. Firefox** : (Version : 46.0.1 and OS Windows 7)

![sub_ff](https://cloud.githubusercontent.com/assets/14175105/16142478/4d26b29e-3483-11e6-90a9-3ddc4aa92cbf.gif)

It's working fine for me. 
Can you please provide your browser and OS version?

**Comment by tarkal** [comment]
It only seems to happen to the twilio plugin and it only seems to be if its the first option selected.

![twilio](https://cloud.githubusercontent.com/assets/7042623/16142790/a65b2c34-3468-11e6-8616-b7fab83dda21.gif)

**Comment by tarkal** [comment]
This happens for both OSX Chrome and Safari.

![screen shot 2016-06-18 at 09 08 13](https://cloud.githubusercontent.com/assets/7042623/16169591/bb9333d6-3534-11e6-9e17-b71e0229dad9.png)

**Comment by sweety-wo** [comment]
Please check it with latest PR. I have solved **templateCacheHtml.js** issue.

Thank you.
