### ISSUE TITLE
Network Incident Query

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#296]
Not sure what query you are using to get the incidents for the network manager but they don't look correct. If you look at the screen shot you will see that all sectors are `INACTIVE` and there are no incidents in the system but the manager is showing loads of incidents. 

![screen shot 2016-06-16 at 08 58 35](https://cloud.githubusercontent.com/assets/7042623/16107987/8bf150da-33a0-11e6-99c6-ca26bcb2eb1b.png)

It should be using the same query used for the incident count in the menu. i.e. `silent=false&state=RED,YELLOW`

**Comment by sweety-wo** [comment]
Yes.... you are right... I didn't used `silent=false&state=RED,YELLOW` in **getIncidents()** API. Now I have used it and incidents not display for `INACTIVE` sector in network graph.

Thank you.
