### ISSUE TITLE
1.3.0 branch shows root node as undefined

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#311]
For some reason the 1.3.0 branch node manager is showing up as undefined.

![screen shot 2016-06-22 at 16 07 57](https://cloud.githubusercontent.com/assets/7042623/16269686/a5c38a62-3893-11e6-8405-82c990f9cfae.png)

**Comment by sweety-wo** [comment]
Is it possible word is repeated in node index? 

Index like : "**BIU_1** > MDCU_1 > **BIU_1** > MDBU_2"

**Comment by tarkal** [comment]
Technically yes it is possible. An engine can repeat nodes. However, that exact one is a bug. I will have a look at it later.

**Comment by sweety-wo** [comment]
Currently I have fixed issue with sector name and word is not is repeated in node 
index like "BIU > ODU1 > DOU1 > BUI1".

I will change my implementation for support repeated word.

**Comment by sweety-wo** [comment]
Fixed #311; 

Changed implementation for support repeated word in index.
Now support  index like: **BIU > BIU > BIU > BIU**

![support_repeated_word](https://cloud.githubusercontent.com/assets/14175105/16337740/50e3c11c-3a35-11e6-9450-b70dd4a68d4d.png)
