### ISSUE TITLE
Firmwares?

### ISSUE THREAD

**Issue by jimwitkin** [ff36/halo-gui#312]
I would suggest changing the menu names from "Firmwares" to "Firmware." 

Also in titles like the attached screen capture, the period at the end is not necessary. And if you do use a period, the US style is to put it inside the ending quote mark.    

![image](https://cloud.githubusercontent.com/assets/18722397/16287862/5ce154c0-389b-11e6-9f00-7155e7f6c684.png)

**Comment by tarkal** [comment]
Agreed. The display value should be in the singular.

**Comment by sweety-wo** [comment]
Okay.. I have changed  "Firmwares" to "Firmware." 

Also, Display value as singular for others like
**Welcome to "Sectors".** to **Welcome to "Sector."**
**Welcome to "Projects".** to **Welcome to "Project."**
**Welcome to "Subscriptions".** to **Welcome to "Subscription."**
**Welcome to "Teams".** to **Welcome to "Team."**
**Welcome to "Users".** to **Welcome to "User."** etc....

@tarkal : Is it OK? 
@tarkal : And for changing in menu you should **changing name** in **http://localhost:8080/api/menus** API response.

**Comment by tarkal** [comment]
@sweety-wo No. The others should be in the plural. Only **firmware** should be in the singular.

**Welcome to "Sectors"
Welcome to "Projects"
Welcome to "Subscriptions"
Welcome to "Teams"
Welcome to "Users"
etc....**

I will take care of the API menu response.

**Comment by sweety-wo** [comment]
okay... np.. I am changing it...

**Comment by jimwitkin** [comment]
fyi, the Manage Halo menu still says Firmwares

![image](https://cloud.githubusercontent.com/assets/18722397/16365271/1e32658a-3bb0-11e6-86cf-7f1ad489b953.png)

**Comment by tarkal** [comment]
We know. This is a dynamic menu bar supplied by the core. It will be pushed with the next core update.
