### ISSUE TITLE
Plugin loader text overlap

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#315]
There is a text overlap when you upload a plugin:

![screen shot 2016-06-24 at 11 21 07](https://cloud.githubusercontent.com/assets/7042623/16333971/927dd70c-39fe-11e6-8e0b-104d21df75df.png)

**Comment by sweety-wo** [comment]
Fixed #315;

![overlap_issue_solved](https://cloud.githubusercontent.com/assets/14175105/16338678/dadb96d2-3a3b-11e6-9cce-78e0a4551f5c.png)
