### ISSUE TITLE
Sector grid layout

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#321]
The sector grid layout does not need so many buttons on it. Each sector only needs 2 buttons. The 'Share' and an 'S' (like the properties 'P'). The default behaviour if you click on the sector should be to go to the node tree view. The 'S' should go to the sector details page. Also lets move the 'i' with the description to the bottom left.

![screen shot 2016-06-28 at 10 21 42](https://cloud.githubusercontent.com/assets/7042623/16409001/a0e26e3c-3d1b-11e6-93c7-3fa4f4f266df.png)

**Comment by sweety-wo** [comment]
I have display only two icons view sector and share. Also add information icon at bottom grid and when click on grid then redirect to nodes tree page.

![sector_grid_ui](https://cloud.githubusercontent.com/assets/14175105/16446111/95ed4efa-3e03-11e6-9da5-29944886260b.png)
