### ISSUE TITLE
Node tree icons

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#322]
We need to modify the icons on the right hand side of the node tree. The top sector row should have the following:

![screen shot 2016-06-28 at 09 59 14](https://cloud.githubusercontent.com/assets/7042623/16409058/f66967b6-3d1b-11e6-84ee-f23ee04590ad.png)

And the rest of the nodes should have:

![screen shot 2016-06-28 at 09 53 56](https://cloud.githubusercontent.com/assets/7042623/16409071/06b8dc0a-3d1c-11e6-9b26-a7e0b62297ad.png)

**Comment by sweety-wo** [comment]
Fixed #322;
![node_tree_icons](https://cloud.githubusercontent.com/assets/14175105/16419953/2b1ffe2e-3d6d-11e6-86aa-bda612301d1f.png)

**Comment by tarkal** [comment]
Don't forget to remove the trash icon from the sector and the silent icon from all the nodes and sector. These are now only present in the sector / node details pages.

**Comment by sweety-wo** [comment]
OK... I will remove it.....

**Comment by tarkal** [comment]
The **S** and the **P** are great but the **N** is very fuzzy and a different color.

![screen shot 2016-06-28 at 17 07 42](https://cloud.githubusercontent.com/assets/7042623/16420826/2096496e-3d53-11e6-8b71-5dca71cd4731.png)

**Comment by sweety-wo** [comment]
Remove deleted and silent icons, Also change sector, node and property icons.

![nodes_icons](https://cloud.githubusercontent.com/assets/14175105/16446008/0bfa4aae-3e03-11e6-8bd0-4786c6476b5f.png)

**Comment by tarkal** [comment]
These are much chunkier than the original designs you had there. I liked the original ones much better. These ones are too blocky and the letters are not properly centralized.

![screen shot 2016-06-29 at 16 25 35](https://cloud.githubusercontent.com/assets/7042623/16455914/50f316aa-3e16-11e6-8214-f1ed74b9cb03.png)

**Comment by sweety-wo** [comment]
Previously I had used  [product-hunt](http://fontawesome.io/icon/product-hunt/)  font awesome icons for P. Font awesome not provided alphabet icons so I have created custom CSS for it. well I will change design like original ones.

**Comment by sweety-wo** [comment]
I have changed icons UI.
 
![halo nodes](https://cloud.githubusercontent.com/assets/14175105/16478899/6d8d01aa-3eba-11e6-9e31-ee4a3e654372.png)

**Comment by tarkal** [comment]
Sorry I still don't like them. :(
Try these: [letters.zip](https://github.com/ff36/halo-gui/files/341667/letters.zip)

**Comment by sweety-wo** [comment]
Okay... I will use letters.zip icons.
Thank you for provide svg icons
