### ISSUE TITLE
Property state ignore

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#323]
If a property has `@ignore` the state marker should have a stroke to show that the state is being ignored by the system when determining the state of the node.

![screen shot 2016-06-28 at 10 00 00](https://cloud.githubusercontent.com/assets/7042623/16409180/8b94d8d4-3d1c-11e6-87f5-cb2b45c43e40.png)

**Comment by sweety-wo** [comment]
If **property** **extra** has `@ignore` then the state marker should have a stroke.
![323](https://cloud.githubusercontent.com/assets/14175105/16419835/c0758f4e-3d6c-11e6-8442-1f78bc2c59b5.png)

**Comment by tarkal** [comment]
This same logic should be applied if the property has `@expression` extra data is present.

**Comment by sweety-wo** [comment]
Solved : status circle border distorted issue in property table at both network and node tree page
![solved_circle_distorted](https://cloud.githubusercontent.com/assets/14175105/16442094/416222c2-3ded-11e6-80da-aac0b3d0c83e.png)

**Comment by sweety-wo** [comment]
Applied same logic if the property has @expression extra data is present.

**Comment by tarkal** [comment]
I think the colours should be slightly different for the two keys. `@ignore` will always be ignored so the property will always be green but the `@expression` needs to be evaluated so can be true or false. Can we try make `@ignore` border green and `@expression` blue?

**Comment by sweety-wo** [comment]
Okay... I will try it..
But if property extra has both @ignore and @expression then display different color?

**Comment by tarkal** [comment]
No `@ignore` always has preference in the code so always look for `@ignore` first and if it is present ... ignore the rest.

**Comment by sweety-wo** [comment]
I have implement it

see 
![status_border](https://cloud.githubusercontent.com/assets/14175105/16482044/c93136aa-3ecb-11e6-94c1-f3d860cb68ff.png)

Is it OK?

**Comment by tarkal** [comment]
What do you think? It looks a little difficult to distinguish the difference on my screen. Try using a light blue maybe to make them stand out a bit.

**Comment by sweety-wo** [comment]
I think use light green instead of green. 
because green circle not looking good for green status property 
see last property of above image.

What do you think?

**Comment by tarkal** [comment]
Give it a go see what it gives.

**Comment by sweety-wo** [comment]
**Light green:**
![light_green](https://cloud.githubusercontent.com/assets/14175105/16482598/1c1fcbc2-3ece-11e6-970d-e0e3d6d8503d.png)

**Light blue**:
![light_blue](https://cloud.githubusercontent.com/assets/14175105/16482615/28d6a278-3ece-11e6-9a80-1b72c288a34f.png)

**Comment by tarkal** [comment]
Well there more visible!!! Perhaps colours are not the best solution! What do you think about using the respective icons next to the state:

![screen shot 2016-06-30 at 11 00 06](https://cloud.githubusercontent.com/assets/7042623/16483031/d68e9e1e-3eb2-11e6-95d5-1016d0e7ec52.png)

This is a much better idea...

**Comment by sweety-wo** [comment]
Done,

![display_icon](https://cloud.githubusercontent.com/assets/14175105/16483983/7cad23d0-3ed4-11e6-8c93-2c46585ad68d.png)

**Comment by tarkal** [comment]
way better.. good job :)
