### ISSUE TITLE
Incident table

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#324]
The incident table needs to be cleaned up.

![screen shot 2016-06-28 at 09 42 36](https://cloud.githubusercontent.com/assets/7042623/16409223/bae92144-3d1c-11e6-9e75-72950c0d8ae4.png)

**Comment by sweety-wo** [comment]
Fixed #324;
![incident table](https://cloud.githubusercontent.com/assets/14175105/16419879/ea356c46-3d6c-11e6-8fe3-bc4c8a7cbaa4.png)
