### ISSUE TITLE
Property sparkline

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#325]
The length of the property boolean and number/precision sparklines should be the same.

![screen shot 2016-06-28 at 12 12 18](https://cloud.githubusercontent.com/assets/7042623/16411904/c3a6d68e-3d29-11e6-88d6-fa718650926b.png)

**Comment by sweety-wo** [comment]
Fixed #325;
![sparkline width](https://cloud.githubusercontent.com/assets/14175105/16487992/bfa2109e-3eeb-11e6-808d-367847834e76.png)
