### ISSUE TITLE
Share grammar

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#326]
The help message should read:

> Select the users with whom you would like to share

![screen shot 2016-06-28 at 12 30 17](https://cloud.githubusercontent.com/assets/7042623/16416457/9e23d8e4-3d42-11e6-9317-d4194d7be3f1.png)

**Comment by sweety-wo** [comment]
I have changed messages

![share_user](https://cloud.githubusercontent.com/assets/14175105/16446396/f2dfb214-3e04-11e6-8366-12219a665445.png)

![share_team](https://cloud.githubusercontent.com/assets/14175105/16446397/f2e03658-3e04-11e6-846c-49292094483a.png)

![share_project](https://cloud.githubusercontent.com/assets/14175105/16446395/f2de4cee-3e04-11e6-83f4-02a6c61c3fba.png)

**Comment by tarkal** [comment]
The Team message should read:
> Select an existing team or create a new one.

The Project message should read:
> Select an existing project or create a new one.

**Comment by sweety-wo** [comment]
Okay.. Changed messages for team and project...
