### ISSUE TITLE
Add link to audits

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#328]
I have removed the main navigation to the audits page as most people don't seem to use it as a main navigation item. Lets add a '**_view all_**' navigation text link at the top of the Audits slide-out by the Latest audits that goes to the audits page.

![screen shot 2016-06-28 at 12 31 45](https://cloud.githubusercontent.com/assets/7042623/16416828/521d4f32-3d44-11e6-85ba-655d6f90ca8c.png)

**Comment by sweety-wo** [comment]
I have added **view all** navigation text link at the top of the Audits slide-out 

![audit_link](https://cloud.githubusercontent.com/assets/14175105/16447660/393250b8-3e0b-11e6-825f-e813bc3c9ea2.png)
