### ISSUE TITLE
Incident report table status

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#329]
The incident table on the incident report page uses big blobs to represent the status. Lets use the same bars as on the incident table page for consistency.

![screen shot 2016-06-28 at 12 27 07](https://cloud.githubusercontent.com/assets/7042623/16416996/ce065530-3d44-11e6-93a4-c2435bf101d8.png)

**Comment by sweety-wo** [comment]
Fixed #329; 
Display status line like incident page in table instead of big blobs

![incident_report_table](https://cloud.githubusercontent.com/assets/14175105/16489084/6951f276-3ef1-11e6-8479-9c8a14cc75c6.png)
