### ISSUE TITLE
Logo name

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#332]
Lets remove the word Halo from the expanded nav menu. The font does not look good so lets get rid of it until we can design something better.

![screen shot 2016-06-28 at 15 55 12](https://cloud.githubusercontent.com/assets/7042623/16418134/dffc79aa-3d48-11e6-8147-321b333f448a.png)

**Comment by sweety-wo** [comment]
I have remove 'HALO' text
![remove _halo](https://cloud.githubusercontent.com/assets/14175105/16449418/0c2f271c-3e15-11e6-85eb-69d06d8f5ff2.png)
