### ISSUE TITLE
No messages message

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#334]
The message displayed in the empty messages table should read:

> You have no messages

![screen shot 2016-06-28 at 12 24 15](https://cloud.githubusercontent.com/assets/7042623/16421529/8aa91226-3d55-11e6-9e89-9474b8a5a6af.png)

**Comment by sweety-wo** [comment]
I have change message.

![no_message](https://cloud.githubusercontent.com/assets/14175105/16446750/be9f3694-3e06-11e6-8a3c-d3a71bd357f4.png)
