### ISSUE TITLE
Incident count

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#335]
Technically when an incident becomes `YELLOW` it is in a state of quarantine but has been resolved. I think we should change the incident count query for the live favicon and the navigation bar label to only include `RED` incidents.

**Comment by sweety-wo** [comment]
Fixed #335;

I have changed incident query for live favicon and the navigation bar label only.

Remove `YELLOW` from incident query.
So, now incident URL is:
http://localhost:8080/api/incidents?perPage=1&**status=RED**&silenced=false&fields=id
