### ISSUE TITLE
Update open property tables

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#336]
If a nodes property table is open it should have transparent periodic updates every 10 seconds.

![screen shot 2016-06-29 at 09 37 34](https://cloud.githubusercontent.com/assets/7042623/16444186/2a59a8b2-3ddd-11e6-8907-64d661b1640c.png)

**Comment by sweety-wo** [comment]
I have set 10 second interval for update property table.

But, still there is one issue, property table flicker when interval call after 10 seconds.

I have used 'angular-datatables' for property table. 
I think I need to change implementation of 'angular-datatables' for support update every 10 seconds.

I am working on it... for support interval update..

**Comment by tarkal** [comment]
ok keep me posted

**Comment by sweety-wo** [comment]
I have changed implementation for update property table but the custom data label icons flick. I need a more time to change transparent update nodes tree and open property table on nodes page.

**Comment by sweety-wo** [comment]
Solved custom data label icons flick issue.
Set interval for each node open properties table.

Currently, spark-line graph create issue when properties table update,
So, for now I hide spark-line graph from properties table at nodes tree page

**Comment by sweety-wo** [comment]
Fixed #336;

Remove angular-datatables library.

For solved spark-line implemented custom-table with `ng-repeat`, search and sort options.
