### ISSUE TITLE
Property updated column

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#337]
The `Updated At` column for properties will always be the same for a given set of node properties. So instead of having `Updated At` column lets just have a single updated statement with the value from the first property in the array.

![screen shot 2016-06-29 at 11 01 58](https://cloud.githubusercontent.com/assets/7042623/16446794/a4f27192-3de9-11e6-859c-fcd5b176d9aa.png)

This should be for the network manager property tables as well.

**Comment by sweety-wo** [comment]
Fixed #337; 
Remove update at from property table for each property and display update time at bottom-right of table

![remove_update_at](https://cloud.githubusercontent.com/assets/14175105/16486740/4d11aafa-3ee4-11e6-97b4-05bb122070fa.png)
