### ISSUE TITLE
Property Edit button

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#339]
The property edit button is not clear enough. Users have stated that its very difficult to find. Lets remove it and add a blue button bottom left with the work 'Edit'.

![screen shot 2016-06-29 at 15 53 52](https://cloud.githubusercontent.com/assets/7042623/16455595/2d47f65e-3e15-11e6-81a9-b0bac5748d34.png)

**Comment by sweety-wo** [comment]
Fixed #339; Removed 'Edit' icon and added a blue button bottom left with the word 'Edit'.

![property_modal](https://cloud.githubusercontent.com/assets/14175105/16478959/c6bee8e2-3eba-11e6-8b0c-ab63d49f7734.png)
