### ISSUE TITLE
Updated Grammar

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#340]
If a time value is relative (e.g. a second ago, 2 mins ago etc.) then the label should be **Updated**. If the time value is absolute (e.g. Tuesday 14:30) the the label should be **Updated at**.

![screen shot 2016-06-29 at 15 16 26](https://cloud.githubusercontent.com/assets/7042623/16455801/f68c8bb0-3e15-11e6-8c2a-9ea3b953421c.png)

N.B. This is universal on the site.

**Comment by sweety-wo** [comment]
Fixed #340; 
Time value is relative then the label 'Updated' and time value is absolute then 'Updated at'.

![update_label](https://cloud.githubusercontent.com/assets/14175105/16478101/23d1483c-3eb5-11e6-9acc-e9f8d575d1bf.png)

![update_at_label](https://cloud.githubusercontent.com/assets/14175105/16478100/23cf9e92-3eb5-11e6-8bf4-d4fa015a2d66.png)
