### ISSUE TITLE
Empty Sector, Team, Project Subscription pages

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#341]
Lets get some slightly better backgrounds for the empty sector, team, project and subscription pages:

Sector:
![empty_sector](https://cloud.githubusercontent.com/assets/7042623/16480686/d708de14-3ea7-11e6-8379-af40fd1a1902.jpg)

Team:
![empty_teams](https://cloud.githubusercontent.com/assets/7042623/16480691/dd274fe2-3ea7-11e6-8782-913c988b8044.jpg)

Project:
![empty_projects](https://cloud.githubusercontent.com/assets/7042623/16480710/ef09a87c-3ea7-11e6-8aba-b53bc2fdc5d1.jpg)

Subscription:
![empty_subscription](https://cloud.githubusercontent.com/assets/7042623/16480715/f63202de-3ea7-11e6-9a9a-4ddf1614f401.jpg)

Here are the icons as SVG:
[empty_icons.zip](https://github.com/ff36/halo-gui/files/340920/empty_icons.zip)

**Comment by sweety-wo** [comment]
Fixed 341; Created UI for Empty Sector, Team, Project Subscription pages.

**Comment by tarkal** [comment]
Couple of points:
- The get started button should open the create modal.
- **_antenae_** should be spelt **_antenna_**
- The 'see more' links should got to the respective page.
- Team text should read:

> Teams are an easy and powerful way of grouping collaborators together so they can access and work on projects co-operatively. The teams permissions dictate the level of actions they can take on the resources in the project.

- Project text should read:

> Projects are containers for holding plugins and sectors that can subsequently be shared with collaborators through teams.

- Plugin text should read:

> Plugins are the life force of Halo. They come in a huge variety of flavours each designed to manipulate a specific aspect of the system to accommodate your requirements. Want to monitor a new piece of hardware? thats a plugin... want to create a custom display? thats also a plugin... how about exporting events to any medium you want in real time? plugin... 

- Plugin page should have the plugin + graphic (the one used for upload a dispatcher) and the get started should open the upload modal.
- Firmware text should read:

> If your hardware manufacturer supports firmware upgrades you can upload the custom Halo firmware packages here to perform bulk firmware management across your entire network with scheduled deployment and role back capability.

- Firmware page should have the plugin + graphic (the one used for upload a dispatcher) and the get started should open the upload modal.

**Comment by sweety-wo** [comment]
**Plugin :**

![plugins](https://cloud.githubusercontent.com/assets/14175105/16581310/80e36126-42c6-11e6-8798-99529df741fe.png)

**Firmware :**

![halo firmware](https://cloud.githubusercontent.com/assets/14175105/16581316/8a195584-42c6-11e6-804b-bd518e25e2cf.png)

I have not open modal on get started button just toggle the upload area.

![halo firmware upload](https://cloud.githubusercontent.com/assets/14175105/16581409/f516f33c-42c6-11e6-8db0-d68344c73edc.png)

**Comment by tarkal** [comment]
Sorry, Plugins and firmware should just have 1 graphic with 'Upload plugin' for the plugins and 'Upload Firmware' for firmware. Get rid of 'Upload dispatcher'.

**Comment by sweety-wo** [comment]
![halo firmware](https://cloud.githubusercontent.com/assets/14175105/16585902/b1a34730-42e0-11e6-97ee-73cd7cd33885.png)

![halo plugins](https://cloud.githubusercontent.com/assets/14175105/16585903/b1a36530-42e0-11e6-9fc1-f8d2575f5b76.png)
