### ISSUE TITLE
Incident link from property table

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#342]
Lets remove the footer link "see incidents" from the properties network table and make the label at the top the link.

![screen shot 2016-06-30 at 14 12 48](https://cloud.githubusercontent.com/assets/7042623/16488817/b0948582-3ed2-11e6-909f-662ad66eeede.png)
![screen shot 2016-06-30 at 14 12 54](https://cloud.githubusercontent.com/assets/7042623/16488818/b0977fda-3ed2-11e6-92eb-4bf01bc1e303.png)

**Comment by sweety-wo** [comment]
Fixed #342; Remove the footer link 'see incidents' and Add 'Incidents:' to label and make it the link.

![add_incidents_label](https://cloud.githubusercontent.com/assets/14175105/16513022/a9342fde-3f7e-11e6-89e9-a3e012f6ad7b.png)
