### ISSUE TITLE
Editing Use Details 

### ISSUE THREAD

**Issue by jimwitkin** [ff36/halo-gui#344]
I found it a little confusing when I was looking at the user detail screen that there was separate section for Teams because the Teams section has its own Edit button. If I want to change details for a user and add him/her to a new team, I've got to click on two edit buttons and two saves (or so it seems). Can you incorporate the Team editing section into the User editing section so I would only have to click Edit and Save once?

![image](https://cloud.githubusercontent.com/assets/18722397/16508031/8f123588-3ee3-11e6-9c91-3c3e3f20970f.png)

**Comment by tarkal** [comment]
I agree. I'm not entirely convinced that the edit button idea is right either. We did try inline a while back but it wasn't as successful as I had hoped but It might be worth revisiting.

Let me do some design thinking and see what we can come up with.

**Comment by tarkal** [comment]
@jimwitkin @er144254 What do you think about this kind of approach:  http://jsfiddle.net/NfPcH/25/

**Comment by jimwitkin** [comment]
@tarkal not sure what you want me to look at. When I click on the Fiddle link I see several lines of code which don't mean much to me (the non programmer)


![image](https://cloud.githubusercontent.com/assets/18722397/16604100/a4334a64-42d6-11e6-8576-da50ab31151e.png)

**Comment by tarkal** [comment]
The bottom right where it ways "awesome user". Click on it.

**Comment by er144254** [comment]
I do agree that we should use a one button edit for the entire screen.  Once in the "edit" mode you should be able to edit the teams as well as the user setup in the top portion.

**Comment by jimwitkin** [comment]
This is definitely an improvement. 

![image](https://cloud.githubusercontent.com/assets/18722397/16636277/e8f04444-438b-11e6-857a-6e0626313923.png)

**Comment by tarkal** [comment]
Ok so @er144254 likes the idea of 1 button to edit all form fields and @jimwitkin likes the individual editable fields. Any other opinions?

**Comment by tarkal** [comment]
@sweety-wo was there a reason we didn't use the x-edit last time?

**Comment by sweety-wo** [comment]
@tarkal 

I think last time we used [angular-xeditable](https://vitalets.github.io/angular-xeditable) ,  It was creating an issue for periodically update the page.  Editable state not maintain when page periodically update.

**Comment by tarkal** [comment]
@sweety-wo can you create a test version using the users details page to see if we can make this work. The detail pages don't need periodic updates so we should be able to remove that requirement.

**Comment by tarkal** [comment]
This has been completed throughout the application. Not just for user details but for all editable fields.
