### ISSUE TITLE
Periodic update of nodes state

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#345]
The node tree icons should be periodically updated with the state of the node. As always it shouldn't interfere or modify the users interface other than update the state.

![screen shot 2016-07-01 at 15 31 57](https://cloud.githubusercontent.com/assets/7042623/16522976/2e0a2818-3fa1-11e6-8e59-5014789879c0.png)

**Comment by sweety-wo** [comment]
I have added periodic transparent update of nodes tree and it will be update after every 10 seconds.
