### ISSUE TITLE
Incident Page 1.3.0

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#348]
The redesigned layout for the incident page for 1.3.0:

![incident_1 3 0](https://cloud.githubusercontent.com/assets/7042623/16553660/2c618788-41ca-11e6-9ab2-882193c957a1.png)

**Comment by sweety-wo** [comment]
I have Created UI for new incident detail page with dummy data.

See:
![new_incident_detail_page](https://cloud.githubusercontent.com/assets/14175105/16585182/2397e782-42dd-11e6-86df-b81eef9bd72a.png)

Currently, incidents are not generated in my local. So, I have commented incident page's 'New UI' code.

Can you tell me 
How to generate incident in my local?

So, I have check new UI with real data.

**Comment by sweety-wo** [comment]
![halo firmware](https://cloud.githubusercontent.com/assets/14175105/16585902/b1a34730-42e0-11e6-97ee-73cd7cd33885.png)

![halo plugins](https://cloud.githubusercontent.com/assets/14175105/16585903/b1a36530-42e0-11e6-9fc1-f8d2575f5b76.png)

**Comment by sweety-wo** [comment]
Display ‘Value’, ‘Row Value’ and ‘Sensitivity’ knob dial
![halo incidents](https://cloud.githubusercontent.com/assets/14175105/16619386/7c7e8558-43ab-11e6-95a5-59b1d29acaf5.png)

Currently, I have display ‘knob dial’ with static data for ‘Value’ and ‘Row Value’.
Can you explain how to display it?
What is max and min value for ‘knob dial’?
Which value display for ‘knob dial’?

**Also**, there is ‘recentValues’ array is blank for 'guiltyProperty' object in get incident API response
I have get following object for incident
{
	"id": "73:2",
	"silenced": false,
	"status": "RED",
	"history": [{
		"time": "2016-07-06T15:33:00+0530",
		"type": "STARTED",
		"status": "RED",
		"details": "Incident automatically detected and created by Halo"
	}],
	"guiltyProperty": {
		"type": "PRECISION",
		"name": "2100AWS : Tx In Power #3",
		"description": "Returns the Transmit (TX) Input power detected on Main Drive Base Station Unit (MDBU) port #3. When no input power is detected, this attribute should return the value -100dBm (decibel-milliwatts).",
		"unitDisplay": "dBm",
		"unitDescription": null,
		"value": "-100.0",
		"maxOperationalValue": "10.0",
		"minOperationalValue": "-20.0",
		"maxAlertValue": "10.0",
		"minAlertValue": "-20.0",
		"alertValue": null,
		"maxAssignableValue": null,
		"minAssignableValue": null,
		"valueDisplayExpression": null,
		"readOnly": true,
		"recentValues": [],
		"silent": false,
		"sensitivity": 50,
		"extra": [],
		"updatedAt": "2016-07-06T15:32:20+0530"
	},
	"guiltyNode": {
		"id": "65:7",
		"name": "MDBU",
		"description": "Main Drive Base Station Unit (M.D.B.U.)",
		"type": "Mdbu",
		"functions": ["OTHER"],
		"index": "Biu > Mdbu_4",
		"reachable": true,
		"firmware": "6.1",
		"status": null,
		"silent": false,
		"extra": [],
		"updatedAt": "2016-07-06T14:49:24+0530",
		"installedAt": "2016-07-06T14:49:24+0530"
	},
	"guiltySector": {
		"id": "61:1",
		"name": "R6 Sector",
		"description": "Testing sector",
		"status": "ACTIVE",
		"silent": false,
		"extra": [],
		"protocol": {
			"id": "4273410683",
			"name": "SOLiD R6 Engine Protocol",
			"model": {
				"port": 20000,
				"ipAddress": "73.34.126.248"
			},
			"fields": null,
			"schedule": "0 0/1 * 1/1 * ? *"
		},
		"createdAt": "2016-07-06T14:48:13+0530",
		"updatedAt": "2016-07-06T18:18:06+0530",
		"owner": null,
		"engine": null
	},
	"details": {
		"name": "Tx In Power #3",
		"cause": "The Tx In Power #3 has exceeded its recommended operational parameters",
		"impact": "Tx In Power #3 Alarm Impact",
		"remedy": "Tx In Power #3 Alarm Remedy",
		"serviceImpact": true,
		"cascadingImpact": true
	}
}

**Comment by tarkal** [comment]
@sweety-wo can you add an issue to the core that the guiltyProperty.recentValues array is null.

The **Value** dial is the EMA value and the range is the `maxOperationalValue` and `minOperationalValue`. The **Raw value** is the non-EMA value (i.e. the actual value) and the range is the same `maxOperationalValue` and `minOperationalValue`.

**Comment by tarkal** [comment]
@sweety-wo If an incident has `guiltyProperty = null` then it means that the incident is due to a connectivity issue so lets use the following design:

![incident_node](https://cloud.githubusercontent.com/assets/7042623/16707091/74e4cd78-45c4-11e6-8868-99fc406efcae.png)

**Comment by sweety-wo** [comment]
![null_property](https://cloud.githubusercontent.com/assets/14175105/16722598/5040c376-4765-11e6-81c2-4927e8195550.png)

Please provide svg image for above.

**Comment by tarkal** [comment]
Here you go:

[path.zip](https://github.com/ff36/halo-gui/files/356605/path.zip)

**Comment by sweety-wo** [comment]
Currently,  I have Display guilty property information like name, description, and silent on left-top side of incident page.

![incident page](https://cloud.githubusercontent.com/assets/14175105/16755617/5006469e-481c-11e6-9968-c8e4e2ba87b3.png)

SO, **What should I display when guilty property is null**?

**Comment by sweety-wo** [comment]
For **Value** and **Raw Value** knob-dial
I have used `maxOperationalValue `and `minOperationalValue `for knob-dial range.

In some incident API response I got following type response for guiltyProperty
there is    
`"maxOperationalValue": "30",`
`"minOperationalValue": "0"`, and 
 `"value": "-8.0"`,

**value is out of range.**

```
  "guiltyProperty": {
    "id": "69:54",
    "alarm": {
      "name": "PD Power #4",
      "cause": "The PD Power #4 has exceeded its recommended operational parameters.",
      "impact": "PD Power #4 Alarm Impact",
      "remedy": "PD Power #4 Alarm Remedy",
      "serviceImpact": true,
      "cascadingImpact": false
    },
    "type": "PRECISION",
    "name": "PD Power #4",
    "description": "PD Power #4",
    "unitDisplay": "dBm",
    "unitDescription": "0.1 dBm Step",
    "value": "-8.0",
    "maxOperationalValue": "30",
    "minOperationalValue": "0",
    "maxAlertValue": "30",
    "minAlertValue": "0",
    "readOnly": true,
    "recentValues": [
      {
        "date": "2016-07-11T18:51:29+0530",
        "value": "-8.0"
      },…],
    "silent": false,
    "sensitivity": 50,
    "extra": [],
    "updatedAt": "2016-07-12T10:38:24+0530"
  }

    "maxOperationalValue": "30",
    "minOperationalValue": "0", and 
    "value": "-8.0",

```

**Comment by tarkal** [comment]
Until `1.4.0` if the value is greater or smaller than a range limit use the value itself as the upper or lower range limit.

**Comment by sweety-wo** [comment]
I have following values 
`"maxOperationalValue": "30"`
`"minOperationalValue": "0"` 
`"value": "-8.0"`

So, for knob-dial range I have used
`var knobMax = value > maxOperationalValue ? value : maxOperationalValue`
knobMax = 30
`var knobMin = value < minOperationalValue ? value : minOperationalValue`
knobMin = -8

**knob-dial range** is **-8 to 30**

If "value": "35" then

`var knobMax = value > maxOperationalValue ? value : maxOperationalValue`
knobMax = 35
`var knobMin = value < minOperationalValue ? value : minOperationalValue`
knobMin = 0

**knob-dial range** is **0 to 35**

**Is it OK?**

**Comment by tarkal** [comment]
for now if it solves the problem then yes

**Comment by sweety-wo** [comment]
Please check this comment 
https://github.com/ff36/halo-gui/issues/348#issuecomment-231938466

**Comment by tarkal** [comment]
Sorry I missed https://github.com/ff36/halo-gui/issues/348#issuecomment-231938466. 

The title should be the `incident.alarm.name`.

The text should be static for the time being:

> The system was unable to establish a connection to ${node.type}.

**Comment by sweety-wo** [comment]
**alarm** object is in **guiltyProperty** not in direct **incident** object or **incident.details**
So, when  guiltyProperty is null then display `incident.details.name` with is same `incident.guiltyProperty.alarm.name`.
and description is **The system was unable to establish a connection to ${node.type}.** 

![halo incidents](https://cloud.githubusercontent.com/assets/14175105/16800969/abd10154-4915-11e6-87c6-e5d34e552311.png)

**Comment by sweety-wo** [comment]
If the guilty sector, node or property has `@cause`, `@impact` or `@remedy` the values displayed under the respective main `@cause`, `@impact` and `@remedy`

![halo incidents extra](https://cloud.githubusercontent.com/assets/14175105/16865567/58729e22-4a83-11e6-8123-ef518bb85834.png)

**Comment by tarkal** [comment]
Looking good
