### ISSUE TITLE
Property Modal 1.3.0

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#349]
The redesigned property modals for 1.3.0:

![property_1_number](https://cloud.githubusercontent.com/assets/7042623/16553715/7bc6cd74-41ca-11e6-87c6-644cbcc5de07.png)

![property_1_boolean](https://cloud.githubusercontent.com/assets/7042623/16553723/885c0c7a-41ca-11e6-9638-e50d78ef729c.png)

![property_1_string](https://cloud.githubusercontent.com/assets/7042623/16553720/84d390aa-41ca-11e6-81ff-8c3f2dd18bdc.png)

**Comment by sweety-wo** [comment]
![new_incident_detail_page](https://cloud.githubusercontent.com/assets/7042623/16553715/7bc6cd74-41ca-11e6-87c6-644cbcc5de07.png)

Can you explain how to display for 'Max', 'Min, and 'Value' knob dial?
What is max and min value for 'Max', 'Min, and 'Value' knob dial?
Which value display for 'Max', 'Min, and 'Value' knob dial?

**Comment by tarkal** [comment]
**Max**
- if `readOnly=true` value = maxAlertValue
- if `readOnly=false` value = maxAssignableValue
- range = value + 30% and value - 30% (In version `1.4.0` it will be possible to edit the max and min. For now use 30% fluctuation).

**Min**
- if `readOnly=true` value = minAlertValue
- if `readOnly=false` value = minAssignableValue
- range = value + 30% and value - 30% (In version `1.4.0` it will be possible to edit the max and min. For now use 30% fluctuation).

**Value**
- value = EMA value
- range = value of Max and value of Min

**Comment by sweety-wo** [comment]
I have following object for **readOnly** true **PRECISION** property

```
{
	"id": "69:338",
	"type": "PRECISION",
	"name": "VHF & UHF : Rx Out Power",
	"description": "Indicates Receive(RX) Voltage. Power is expressed in dB (Decibels).Valid Power levels for Receive(RX) path range from 0volt to +100dBm.",
	"unitDisplay": "dBm",
	"unitDescription": "dBm",
	"value": "-100.0",
	"maxOperationalValue": "100",
	"minOperationalValue": "-100",
	"maxAlertValue": "1",
	"minAlertValue": "-30",
	"alertValue": null,
	"maxAssignableValue": null,
	"minAssignableValue": null,
	"valueDisplayExpression": null,
	"readOnly": true,
	"recentValues": [{ "date": "2016-07-07T16:47:13+0530", "value": "-100.0" },.....],
	"silent": false,
	"sensitivity": 50,
	"extra": [],
	"updatedAt": "2016-07-07T17:16:07+0530"
}

```

So,

**Max**  : 
if readOnly=true value = maxAlertValue
**`value = 1`**

range = value + 30% and value - 30% 

range = 1 + ( 1 * (30 / 100))  and 1 - ( 1 * (30 / 100)) 
**range = 1.3 and 0.7**
So, for **MAX** `maxRange = 1.3` and `minRange = 0.7`

**Min** : 
if readOnly=true value = minAlertValue
**value = -30**

range = value + 30% and value - 30% 
range = -30 + ( -30 * (30 / 100))  and -30 - ( -30 * (30 / 100)) 
range = -39 and -21
So, for **MIN** `maxRange = -21` and `minRange = -39`

**Value** :
suppose EMA array is ["-100", "-100", "-100",**"-100"**,]

So,
value = last value of EMA array
`value = -100`

range = value of Max and value of Min
So, for **Value** `maxRange = 1` and `minRange = -30`

Is above calculation is OK?

**Comment by tarkal** [comment]
Yes that is correct. As I mentioned before in `1.4.0` the property object will be modified to allow the respective min and max to have ranges but for now that calculation is fine.

Important correction! I made a mistake in the mockups. The **Min** should be on the left and the **Max** should be on the right.

**Comment by sweety-wo** [comment]
But 
For **Value** :
value = -100
and range is  Value maxRange = 1 and minRange = -30

value**(-100)** is out of range**(-30 to 1)**

**Comment by tarkal** [comment]
Yes correctly that is why that value would be in an alert state. However I can see that this would be a problem graphically.

Lets change **Min** and **Max** values to:

**Max**
- if `readOnly=true` value = `maxOperationalValue`

**Min**
- if `readOnly=true` value = `minOperationalValue`

**Comment by sweety-wo** [comment]
okay.. 
I have use maxOperationalValue for Max  and minOperationalValue for min.

Now, calculation result for above object:

**Max**:
`value = 100`
`range = 70 to 130`

**Min**:
`value = -100`
`range = -130 to -70`

**Value**:
`value = -100`
`range = -100 to 100`

**Graphical image**:
![halo property](https://cloud.githubusercontent.com/assets/14175105/16653847/9cf4b986-4470-11e6-9fe0-bfef821769ad.png)

**Comment by tarkal** [comment]
Thats good. (don't forget to put the max on the right and the min on the left)

**Comment by sweety-wo** [comment]
![halo property](https://cloud.githubusercontent.com/assets/7042623/16553720/84d390aa-41ca-11e6-81ff-8c3f2dd18bdc.png)

I got following response for string property

```
{
	"id": "69:286",
	"type": "STRING",
	"name": "VHF & UHF : Name",
	"description": "Very High Frequency Ultra High Frequency Name ",
	"value": "Tarkas UHF",
	"readOnly": false,
	"recentValues": [{
		"date": "2016-07-08T16:46:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:47:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:48:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:49:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:50:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:51:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:52:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:53:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:54:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:55:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:56:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:57:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:58:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T16:59:06+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:00:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:01:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:02:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:03:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:04:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:05:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:06:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:07:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:08:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:09:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:10:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:11:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:12:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:13:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:14:05+0530",
		"value": "Tarkas UHF"
	}, {
		"date": "2016-07-08T17:15:05+0530",
		"value": "Tarkas UHF"
	}],
	"silent": false,
	"sensitivity": 50,
	"extra": [],
	"updatedAt": "2016-07-08T17:15:05+0530"
}
```

I got string in 'recentValues' value,
SO, Please explain how to create graph for **string**  property.

**Comment by tarkal** [comment]
There are a couple of ways to do it. We might need to try out a few to find the best one. The idea is just to make the string into a numerical hash. Try something like this:

```
hashCode = function(str){
    var hash = 0;
    if (str.length == 0) return hash;
    for (i = 0; i < str.length; i++) {
        char = str.charCodeAt(i);
        hash = ((hash<<5)-hash)+char;
        hash = hash & hash; // Convert to 32bit integer
    }
    return hash;
}
```

**Comment by sweety-wo** [comment]
I have used it.

Generate following chart
![string_property](https://cloud.githubusercontent.com/assets/14175105/16687379/ea43c5f4-4535-11e6-9dd3-de92ec31a5cc.png)

**Comment by sweety-wo** [comment]
![string_property](https://cloud.githubusercontent.com/assets/14175105/16687602/4133237c-4537-11e6-8303-01ee3f25c065.png)

**Comment by sweety-wo** [comment]
Currently, **new property UI** modal open from node tree view page, I have not opened it form network page so, **old property modal** open form network page.

Please give a feed back for Property modal.

Can you please provide documentation for new property UI to
 what should I do for different type property? Or what should I do when property is **readOnly** true or false?
Like about value Edit, sensitivity Edit, and use of EMA etc…

**Comment by sweety-wo** [comment]
I have change Property modal UI
![property modal](https://cloud.githubusercontent.com/assets/14175105/16732170/65a8a8b2-4799-11e6-8d7d-cae3fadb9d23.png)

**_Following condition use for Property Modal_**
**If property readOnly=true and type is boolean, number or precision;**

- Display sensitivity (Knob - Dial) with edit option (sensitivity Editable);
- Display value (Knob - Dial) without edit option  (value not editable)
- Value = last value of EMA;
- Display chart from EMA values


**If property readOnly=false and type is boolean, number or precision;**

- Display sensitivity (Knob - Dial) without edit option (sensitivity not Editable);
- Display value (Knob - Dial) with edit option (value editable) 
- Value = value;
- Display chart from recentValues


**If property readOnly=true and type is string:**

- Display sensitivity (Knob - Dial) with edit option (sensitivity Editable);
- Display chart with 'hashCode' function which given by you
	```
var hashCode = function(str){

		var hash = 0;

		if (str.length === 0) { return hash; }

		var i = 0;

		for (i; i < str.length; i++) {

			var char = str.charCodeAt(i);

			hash = ((hash<<5)-hash)+char;

			hash = hash & hash; // Convert to 32bit integer

		}

		return hash;

	};
```
- value = value;

**If property readOnly=false and type is string:**

- Display sensitivity (Knob - Dial) without edit option (sensitivity not Editable);
- Display chart with 'hashCode' function which given by you 
	```
var hashCode = function(str){

		var hash = 0;

		if (str.length === 0) { return hash; }

		var i = 0;

		for (i; i < str.length; i++) {

			var char = str.charCodeAt(i);

			hash = ((hash<<5)-hash)+char;

			hash = hash & hash; // Convert to 32bit integer

		}

		return hash;

	};
```
**value = value;**

Is it OK?

**Comment by tarkal** [comment]
Lets remove the fill from the numerical chart so its just a line. The fill looks good but its confusing depending on the property.

![screen shot 2016-07-12 at 11 25 35](https://cloud.githubusercontent.com/assets/7042623/16762161/9ad4228e-4823-11e6-876e-426722c886c1.png)
