### ISSUE TITLE
Property Modal Editable Number

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#363]
In the property modal if a property is editable (`readOnly=false`) and it is of type `Number` the input for the value should not be a `Precision`.

![screen shot 2016-07-12 at 12 24 44](https://cloud.githubusercontent.com/assets/7042623/16766908/fffb46a6-483c-11e6-9cef-28a7a087c349.png)

**Comment by sweety-wo** [comment]
Fixed #363
if property is editable (readOnly=false) and it is of type **Number** then knob-dial **step is 1** 
and
if property is editable (readOnly=false) and it is of type **PRECISION** then knob-dial **step is 0.1** 

also, changed dial font style like mock-up image black font and size, display unit after value

![halo nodes](https://cloud.githubusercontent.com/assets/14175105/16767250/2a12c9ea-485c-11e6-89e7-0805c6572ccc.png)
