### ISSUE TITLE
New Sector Message

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#370]
The toaster message for new sectors should read:

> The authenticity and connectivity to your sectors root node has been successfully verified. Grab a cup of coffee while your network is discovered and configured. 

![screen shot 2016-07-07 at 13 19 07](https://cloud.githubusercontent.com/assets/7042623/16874911/854c63d8-4a9c-11e6-83ad-fbd067c8048d.png)

**Comment by sweety-wo** [comment]
Fixed #370; Changed new sector create message 

![sector_create_msg](https://cloud.githubusercontent.com/assets/14175105/17208935/6a1f6286-54d8-11e6-8905-ab06d5cf6321.png)
