### ISSUE TITLE
Empty Sector in grid

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#371]
After you first create a sector and it loads into the sectors grid the box is empty. People are impatient! If the node tree is empty lets get a loader in there with a message.

> One moment while we auto discover your sector

![screen shot 2016-07-09 at 15 47 02](https://cloud.githubusercontent.com/assets/7042623/16875111/e44364b2-4a9d-11e6-9355-4b85fa69e433.png)

**Comment by sweety-wo** [comment]
Fixed #371;  If the node tree is empty lets get a loader in there with a message 'One moment while we auto discover your sector'

![sector_node_tree _loader](https://cloud.githubusercontent.com/assets/14175105/17209532/0e3f59d2-54db-11e6-8af8-7be2479b4094.gif)
