### ISSUE TITLE
Plugin grid design

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#372]
The plugin grid design should be changed to the following:

![screen shot 2016-07-12 at 11 50 21](https://cloud.githubusercontent.com/assets/7042623/16875149/1d0f59b8-4a9e-11e6-95f5-08c969fe6fe9.png)

The ... button should contain the same as the current actions menu. Plugins can be shared exactly like sectors so we need the share wizard.

The icons are for the different types of plugin. I will add them shortly.

**Comment by sweety-wo** [comment]
Please give me SVG image for it..

**Comment by sweety-wo** [comment]
I have changed plugin grid design 

See following images
![halo plugins](https://cloud.githubusercontent.com/assets/14175105/17361464/46fb69f2-598e-11e6-81bb-ad7ce490e7b1.png)
![halo plugins_menu](https://cloud.githubusercontent.com/assets/14175105/17361465/470016c8-598e-11e6-9cbd-b80960f5276b.png)


Please provide **Chip SVG image** SO I will replace with existing image

Also, please provide mock-up for plugin share wizard.
What is required for plugin share user, team or project?

**Comment by sweety-wo** [comment]
I have created share wizard for plugin share
Same as **sector** share wizard.


![halo share](https://cloud.githubusercontent.com/assets/14175105/17363679/7ff11260-5999-11e6-9d00-b1933928793f.png)

Is it OK?
