### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#375]
We should display the core version number in the authenticated page footer. See this issue to obtain the version: https://github.com/ff36/halo-core/issues/90

**Comment by sweety-wo** [comment]
I have made code for display version in footer
See following image
![halo_version](https://cloud.githubusercontent.com/assets/14175105/17018663/6bfd8240-4f56-11e6-9e0c-023db99ec194.png)

**Still, there is one issue** 
I have get 'X-Halo-Version' in response header 
![response header](https://cloud.githubusercontent.com/assets/14175105/17018783/0507e2b4-4f57-11e6-8a2f-f89deeb0583b.png)

But, can't read the header on JavaScript.

[**I think need to allow the client to read the header.** ](http://stackoverflow.com/questions/32404092/response-header-is-present-in-browser-but-not-parsed-by-angular-http-response-h?answertab=votes#tab-top)

**Comment by tarkal** [comment]
I have added this in latest version.

**Comment by tarkal** [comment]
Move it over to the left. There is a problem with it centralised for mobil devices.

![screen shot 2016-07-25 at 11 15 20](https://cloud.githubusercontent.com/assets/7042623/17096464/c8331754-5259-11e6-9085-ddf41ebecb13.png)

**Comment by sweety-wo** [comment]
Done.

![version](https://cloud.githubusercontent.com/assets/14175105/17100391/b6861cb8-528b-11e6-8210-eae75d9d86e9.png)
