### ISSUE TITLE
Remove required extra data values validation

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#385]
Some extra data do not require values to be entered and it is causing a problem because users are forced to enter values when they are not needed.

I think for the short term lets remove the validation. In the future we can look to add a `validation` variable to the Extra object.

![screen shot 2016-07-25 at 16 15 11](https://cloud.githubusercontent.com/assets/7042623/17104471/513cbfa4-5283-11e6-9db7-f39a1ad1ea8f.png)

**Comment by sweety-wo** [comment]
Fixed #385; Remove required extra data values validation 
only required validation apply for `@latitude` and `@longitude`
![halo nodes](https://cloud.githubusercontent.com/assets/14175105/17211042/9c4fce56-54e4-11e6-98c1-f3b42630f41c.png)

If you think also remove validation for `@latitude` and `@longitude`
then tell me I will remove it.
