### ISSUE TITLE
Remove node tree property eye

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#386]
The eye button in the property table does the same as clicking on the row itself so we can remove it.

![screen shot 2016-07-25 at 12 12 04](https://cloud.githubusercontent.com/assets/7042623/17107147/51795b02-528e-11e6-8dcb-d1a44dc7bfad.png)

**Comment by sweety-wo** [comment]
Fixed #386; Remove node tree property eye from property table

**Comment by sweety-wo** [comment]
![halo nodes](https://cloud.githubusercontent.com/assets/14175105/17210524/1cb6d192-54e1-11e6-8026-f3def48f1055.png)
