### ISSUE TITLE
Sidebar icons could be optimized

### ISSUE THREAD

**Issue by ActionCactus** [ff36/halo-gui#389]
As it currently stands Halo defaults to a collapsed sidebar.  Ideally this should be configurable on a user-to-user basis (so I could choose to have it expanded by default, while you could have it collapsed), but regardless of how it looks on page load the icons could be modified to more immediately portray what that view contains.  Thoughts on each icon are as follows:

Dashboard - this works.  The average English-speaking human being in the 21st century will correspond "dashboard" with a speedometer/odometer like the one that is portrayed.

Incidents - works very well.  It is immediately apparent what this view will display

Networks - This works well with both the Networks and Sectors icons; that's the problem.  What is displayed on this page has layers in the bar forms like what it currently shows, but it's also circular and behaves as you would expect the Sectors icon would.  Suggestions would be to change the Sectors icon (see below) and either keep the current Networks icon or modify it to more strongly represent the view it displays.  Excuse my absolutely HORRENDOUS artistic abilities, but something like this:

![image](https://cloud.githubusercontent.com/assets/17009372/17145434/1ff37cee-5328-11e6-84ef-7ef3c2aa5849.png)

...you'd just want to make it look about 20x nicer.  What something like this accomplishes is a more obvious correlation between the icon and the page itself.  The problem it presents is that it's larger and would therefor have to be compressed down to a point that might not actually be legible.  What i'd suggest, then, is that you reduce the number of bars from 4 to 3 and split the circle in to 3 well-defined portions with larger bars.  It would be even more apparent then.

Sectors - Again, you want something more strongly correlated with the UI that is displayed.  The current pie chart would work if it wasn't similar to what is displayed on the Networks page, so I'd suggest something more along the lines of this (again, a real artist would be able to do this much better):

![image](https://cloud.githubusercontent.com/assets/17009372/17145692/3bb6f1b2-5329-11e6-9967-abc68cc33904.png)

Teams - Right now the icon is pretty good, but it's hard to pick out exactly what it is until you read "teams". I would suggest throwing the people icons side-by-side, rather than ordered, in order to make it obvious that the team members are people, not something like a fat, short-winged beetle trying to fly.

Projects - works fine, I think.

Subscriptions - this is tough.  You're trying to create an icon for a very abstract concept, even more abstract than those above.  If you look at major social networking sites (as I'm sure you've studied for inspiration) you will notice that even the uber-popular, multi-billion dollar corporations with highly advanced UX departments composed of the best designers in the world can't usually come up with anything better than "Subscribe", often with the site's icon.  I think the pound sign generally suits the purpose here, especially since much of this will be through messaging, but it's not immediately obvious what really goes on in this view.  The only other suggestion I would have would be a mail icon, but like what gmail has, but it is similar to what exists.

Reports - perfect

Manage Halo - you use a database icon, which is suiting, but I look at that and think of properties/sectors/incidents, not plugins and users.  I'd suggest changing this to a cog or a wrench to go along with something more widely used.

A final suggestion: it's not immediately obvious that the antenna/angel icon at the top is what expands the taskbar.  I would suggest rendering a glow / highlight, or even adding an "expand" text to the icon itself when a user hovers over the collapsed sidebar.  This will draw their attention to it.

**Comment by ActionCactus6** [comment]
I forgot to mention Teams.  Right now the icon is pretty good, but it's hard to pick out exactly what it is until you read "teams".  I would suggest throwing the people icons side-by-side, rather than ordered, in order to make it obvious that the team members are people, not something like a fat, short-winged dragonfly spreading its wings.

**Comment by ActionCactus** [comment]
Sorry for commenting and commenting with 2 different user accounts :)

**Comment by tarkal** [comment]
@hiteshk12, @jimwitkin, @er144254, @tblake84 
As system users instead of designers any thoughts on this suggestion?

**Comment by jimwitkin** [comment]
I generally agree that the menu icons should correlate with how the function is displayed in the UI, but I'm not bothered by the current icons. The most important thing is that they are used consistently through the program. I use a cloud-based program called Paymo to track my hours and generate invoices. It uses a very similar sidebar to Halo. It simply offers an arrow (like greater than / less than symbols) to allow the user to expand or collapse the menu. This works fine for me.
See attached graphics.

[Paymo Menu - Collapsed and Expanded.docx](https://github.com/ff36/halo-gui/files/386476/Paymo.Menu.-.Collapsed.and.Expanded.docx)

**Comment by er144254** [comment]
As a user I very rarely pay much attention to the icons.  I pay more attention to the float over labels.  That doesn't make it right.  I would be fine with changing the icons to something that might be more representative, but at this point I would prioritize a little bit lower as core functionality is more important in my eyes.

**Comment by tarkal** [comment]
I have no problems with changing some icons. I will look at some optional designs. I do think that its a good idea to remember the users menu expanded/collapsed choice. 

@sweety-wo Lets go ahead and create a client side storage setting to remember the users preferred navigation collapse or expanded preference. Lets work with the following logic:

- By default if no preference exists lets have it collapsed. 
- Once a either collapses or expands the navigation store the preference locally.

I will post new icons here when they are done.

**Comment by sweety-wo** [comment]
I have store menu expanded/collapsed preference locally

By default if no preference exists lets have it collapsed.
when menu expanded then store `true` otherwise store `false`.

if menu expanded preference is store  as `true`  in locally and page refresh then user display  expanded  menu otherwise display collapsed menu.

![menu](https://cloud.githubusercontent.com/assets/14175105/17506822/8a7984c6-5e29-11e6-948f-1fd4784d89a6.gif)

@tarkal  Is it OK?

**Comment by tarkal** [comment]
@sweety-wo I have modified the navigation icons. Can you please modify the following to match:

![screen shot 2016-08-13 at 12 54 16](https://cloud.githubusercontent.com/assets/7042623/17668901/bb0372aa-630b-11e6-8d86-ceb7df152dcc.png)

![screen shot 2016-08-15 at 17 10 47](https://cloud.githubusercontent.com/assets/7042623/17668957/04bf0d82-630c-11e6-8339-a6669aa33e2b.png)

**Comment by sweety-wo** [comment]
Changed icons

![halo dashboard](https://cloud.githubusercontent.com/assets/14175105/17694104/e11831ec-63bf-11e6-8fa7-95394545b3cb.png)
![halo sector](https://cloud.githubusercontent.com/assets/14175105/17694105/e11ff3dc-63bf-11e6-9cd8-fcb5632f328a.png)
