### ISSUE TITLE
Sector state change button

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#393]
When you click on the sector status change the selected button does not display its correct colour straight away. Instead it just goes grey until you click somewhere in the screen.

![screen shot 2016-07-28 at 10 47 10](https://cloud.githubusercontent.com/assets/7042623/17206701/43c05cfc-54b1-11e6-99cf-c44db72bf692.png)

**Comment by sweety-wo** [comment]
Fixed #393;

![sector_state_button](https://cloud.githubusercontent.com/assets/14175105/17207801/ca8c0282-54d3-11e6-97d5-206a49a61bf4.gif)
