### ISSUE TITLE
Remove custom data from new Sector modal

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#396]
Generally speaking most users are not adding extra data to the sector at creation time. I suggest we remove the accordion and just have the sector registration in the modal.

![screen shot 2016-07-29 at 17 57 09](https://cloud.githubusercontent.com/assets/7042623/17269623/c2b1eef2-564d-11e6-9c51-f84383bf667e.png)

**Comment by sweety-wo** [comment]
You mean remove accordion panel and just display basic information form in sector modal or 
display both basic information and custom data from without accordion panel?

**Comment by tarkal** [comment]
yes

**Comment by sweety-wo** [comment]
I have remove accordion panel and custom data section form create sector modal

![halo sectorsmodal](https://cloud.githubusercontent.com/assets/14175105/17317461/8ec1eb2e-589b-11e6-90f8-f87cdc900395.png)

@tarkal : Is it OK?
