### ISSUE TITLE
Version position

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#397]
The version position might be better next to the copyright footer.
![screen shot 2016-07-29 at 17 51 31](https://cloud.githubusercontent.com/assets/7042623/17269664/05f4e308-564f-11e6-8e28-b60abe674d0f.png)

**Comment by sweety-wo** [comment]
Done.
![footer](https://cloud.githubusercontent.com/assets/14175105/17285708/14260f26-57e2-11e6-9604-6ea39e64f26e.png)
