### ISSUE TITLE
Color coded percentile bar

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#398]
At the top of all the network / tree orientated pages lets add a color coded mini bar that breaks down the % of nodes in each state.

![screen shot 2016-07-30 at 12 13 51](https://cloud.githubusercontent.com/assets/7042623/17269749/4a8d5a52-5651-11e6-9fdd-31e0674e1f28.png)

Assuming the width of the container to be 100% show the % nodes in each state in their respective colors.
![screen shot 2016-07-30 at 12 22 01](https://cloud.githubusercontent.com/assets/7042623/17269755/802d8254-5651-11e6-821c-e2fcef2fb9db.png)
![screen shot 2016-07-30 at 12 21 33](https://cloud.githubusercontent.com/assets/7042623/17269756/80304aac-5651-11e6-9f20-4a18706df5a7.png)

**Comment by sweety-wo** [comment]
Done.

I have created custom directive for Color coded percentile bar

See following images:

![halo networks](https://cloud.githubusercontent.com/assets/14175105/17295417/a73a0600-5819-11e6-9644-da53465eeb57.png)
![halo nodes](https://cloud.githubusercontent.com/assets/14175105/17295418/a73c130a-5819-11e6-95e3-f243101c0336.png)
![halo sectors](https://cloud.githubusercontent.com/assets/14175105/17295419/a73d5670-5819-11e6-9320-23e003cfb330.png)

**Comment by tarkal** [comment]
Lets half the thickness of the line.
