### ISSUE TITLE
@inactive

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#400]
If a property contains `@inactive` in the extra data the row should be faded to 15% opacity. For now keep all the functions active just fade it out. 

The back end will be modified to prevent incidents for `@inactive` tags.

**Comment by tarkal** [comment]
@sweety-wo ignore this issue!

**Comment by sweety-wo** [comment]
15% opacity not look good 
So, I have apply 50% opacity on table row which contains @inactive in the extra data 

see following image
![halo nodes](https://cloud.githubusercontent.com/assets/14175105/17325405/0e08a1de-58c9-11e6-8f92-4dcc238c3211.png)

**Is it OK?**

**Comment by tarkal** [comment]
that is great for now.
