### ISSUE TITLE
Sector tree cluttered

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#405]
The tree diagram in the sector grid page works fine for small numbers of nodes but it becomes a real mess when there are lots of nodes.

![screen shot 2016-08-04 at 16 40 21](https://cloud.githubusercontent.com/assets/7042623/17431831/377f17b6-5afc-11e6-8e24-3bc5f0de23d7.png)

@sweety-wo What do you think about implementing the sunburst instead? Its more scalable.

![screen shot 2016-08-04 at 16 40 21 2](https://cloud.githubusercontent.com/assets/7042623/17431852/500e9f90-5afc-11e6-830f-9d065cc796af.png)

**Comment by sweety-wo** [comment]
I think about implementing the sunburst instead tree its good for sector grid.  let me try to do this.

**Comment by tarkal** [comment]
Lets load the incidents asynchronously or remove them. Currently loading the sectors grid with multiple sectors and lots of incidents takes a huge amount of time.

**Comment by sweety-wo** [comment]
Okay..
I have remove  incidents ring from network of sector grid page.
