### ISSUE TITLE
Heat Map Cal

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#407]
Ok I think the heat-map calendar is starting to look really good. There are some problems with the responsiveness. On a larger screen there everything is clustered on the left and on a mobile screen you cant get to the dates off screen.

![screen shot 2016-08-06 at 11 48 23](https://cloud.githubusercontent.com/assets/7042623/17456102/3e07a9ce-5bcc-11e6-8de8-aec20dbc5968.png)

![screen shot 2016-08-06 at 11 49 44](https://cloud.githubusercontent.com/assets/7042623/17456104/41916a80-5bcc-11e6-8457-36915349a424.png)

Can we look at dynamically adjust the spacing and/or range to fill the available space. The `Active`, `Started`, `Ended` toggle is floating in the middle of the page.

**Comment by sweety-wo** [comment]
I have checked cal-heat map responsive but currently its not supported yet. Please see this GitHub issue link https://github.com/wa0x6e/cal-heatmap/issues/157.  I think we need to manually set it's spacing and/or range.

**Comment by tarkal** [comment]
Ok, lets centralize it on the page and hide it for mobile until the responsive aspect is ready.
