### ISSUE TITLE
Node tree not ending correctly

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#411]
The node tree does not seem to end neatly. 

![screen shot 2016-08-09 at 13 44 46](https://cloud.githubusercontent.com/assets/7042623/17542485/751fb866-5ec9-11e6-8160-50ed686739d4.png)

**Comment by sweety-wo** [comment]
When all properties table open then issue is created

I have fixed it.
Please check it...

![halo nodes](https://cloud.githubusercontent.com/assets/14175105/17578868/326e9dfa-5fac-11e6-92a0-63d1dff3fde0.png)
