### ISSUE TITLE
Sunburst path logic

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#414]
The sunburst path display is confusing people because its displaying the last node that the mouse was over.

![screen shot 2016-08-11 at 10 10 04](https://cloud.githubusercontent.com/assets/7042623/17582427/e78f18d2-5fab-11e6-8b27-ad1ecf1fd3b3.png)

The logic should be as follows:

- The path should display the node that the mouse is currently on. If the mouse is not on any node the path should be the `selected node`.
- The `selected node` should be the node that has been selected to display its properties. If no node is selected the `selected node` should be empty.

**Comment by sweety-wo** [comment]
Done...

Please check it..

![iwvsxt7oiy](https://cloud.githubusercontent.com/assets/14175105/17615884/cae9658c-608e-11e6-8d8e-69ff0ae803d2.gif)

**Comment by tarkal** [comment]
This works great now except when no node has been selected. If no node properties are selected the fallback default should be an empty path.

**Comment by sweety-wo** [comment]
Done.
On mouse out from network graph and no node selected for property then breadcrumb path not display.
![node path](https://cloud.githubusercontent.com/assets/14175105/17844079/3536cfee-6853-11e6-82b9-52bfe702f5fa.gif)
