### ISSUE TITLE
Property table extra data 

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#417]
The extra data icon in the property table should be far right. Currently its floating. Also lets remove the box around the button and just make it an icon.

![screen shot 2016-08-11 at 16 26 38](https://cloud.githubusercontent.com/assets/7042623/17592012/e2f2a28c-5fe0-11e6-99c8-b2a0d1873e98.png)

**Comment by sweety-wo** [comment]
Done..

![halo nodes](https://cloud.githubusercontent.com/assets/14175105/17616966/fd5610fa-6094-11e6-904e-0ded2a0819de.png)
