### ISSUE TITLE
User priority

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#420]
Currently if an API request is delayed the GUI page does not complete loading and blocks. It is then not possible to use the navigation buttons or on the sectors grid its not possible to click on the sector to see the tree etc. 

We need to prevent this blocking. Users should be able to click on buttons regardless of if the page has completed loading.

**Comment by sweety-wo** [comment]
Sent  per page only 1 for user API call to page resolved
Please check Still issue occur?
