### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#421]
There seems to be an error when loading the GUI after a season has expired. If a session is established and then the user leaves the computer and the session expires, when the user clicks refresh the GUI displays an empty blue screen instead of loading the login page.

**Comment by sweety-wo** [comment]
Done.

Display limited access page when page resolve user API call not respond in 15 seconds, When serve stop and reload the GUI then redirect on lock screen.
Fixed #420; per page sent only 1 for page resolved user API call.

![6sbt0tjcdk](https://cloud.githubusercontent.com/assets/14175105/17665833/ccd20e42-631a-11e6-863a-0b09c7704184.gif)
