### ISSUE TITLE
Sector grid sunburst label

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#422]
The hover label over the sector grid sunburst should be the index instead of the name.

![screen shot 2016-08-12 at 13 31 32](https://cloud.githubusercontent.com/assets/7042623/17661840/e0c9efc0-62e1-11e6-8b85-d8d291ec14e6.png)

**Comment by sweety-wo** [comment]
Done.

Display node index instead of the node name when hover over the sector grid sunburst

![sector](https://cloud.githubusercontent.com/assets/14175105/17689506/d0b281e6-63a5-11e6-989e-94ac6cae3e3e.png)
