### ISSUE TITLE
Incident count favicon

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#424]
The incident count in the tab gets cut off when you get over 2 hundred:

![screen shot 2016-08-12 at 09 33 12](https://cloud.githubusercontent.com/assets/7042623/17661907/519334f0-62e2-11e6-97f9-50d3468d5556.png)

**Comment by sweety-wo** [comment]
count label only display in favicon image size place.

**Comment by sweety-wo** [comment]
one option is display incident count is this way 
see image

![count](https://cloud.githubusercontent.com/assets/14175105/17691397/cbe812f0-63b1-11e6-93df-65857967a1c0.png)

**Comment by tarkal** [comment]
I prefer the live favicon. When it reaches +1000 it is displayed as 1K etc. So we just need to modify the CSS so make the 100-999 fit.

**Comment by sweety-wo** [comment]
I have all ready maintain it.

  ```
 if (num >= 1000000000) {
                    return (num / 1000000000).toFixed(1).replace(/\.0$/, '') + 'G';
                }
                if (num >= 1000000) {
                    return (num / 1000000).toFixed(1).replace(/\.0$/, '') + 'M';
                }
                if (num >= 1000) {
                    return (num / 1000).toFixed(1).replace(/\.0$/, '') + 'K';
                }
```

but 100-999 out of space.
I have also check it on demo sit
http://dirkgroenen.nl/tinycon-angularjs/demo/

There is same issue.

I will try to make the 100-999 fit

**Comment by tarkal** [comment]
Can you just reduce the font size slightly?

**Comment by sweety-wo** [comment]
I am tying it...

**Comment by sweety-wo** [comment]
![count](https://cloud.githubusercontent.com/assets/14175105/17692777/4b7b4f8a-63b9-11e6-952c-4cd3cf36a062.png)

Is it OK?

**Comment by tarkal** [comment]
Looks good. Check it with 999.

**Comment by sweety-wo** [comment]
I have already check it.. 
It's look fine and fit.
see...
![count](https://cloud.githubusercontent.com/assets/14175105/17692904/f36ed23e-63b9-11e6-8a36-9a8369805ddf.png)

**Comment by tarkal** [comment]
good job.
