### ISSUE TITLE
Sector details spacing

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#428]
The sectors details page should have spacing between the Protocol panel and the Schedule panel. Also I know the Protocol is loaded using Angular formly but the Schedule is not so we could add xeditable to the schedule?

![screen shot 2016-08-15 at 11 57 55](https://cloud.githubusercontent.com/assets/7042623/17668657/a43ce89a-630a-11e6-8e59-d208e9c81f4b.png)

**Comment by sweety-wo** [comment]
Schedule is belongs to Protocol.
So I have not use xeditable  for Schedule.
and display in project section...
by mistake I have display separate title for Schedule.

So, should I use xeditable for Schedule?

**Comment by tarkal** [comment]
The above is fine. It was just the separator that looked odd.
