### ISSUE TITLE
Subscription details edit

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#429]
The edit icon for the subscriptions details page should be like the new edit icons.

![screen shot 2016-08-15 at 16 54 24](https://cloud.githubusercontent.com/assets/7042623/17668989/2b41274c-630c-11e6-801f-94c9231b5362.png)

**Comment by sweety-wo** [comment]
Used edit button instead of edit icon
![halo subscription](https://cloud.githubusercontent.com/assets/14175105/17698097/b46fa82a-63d6-11e6-88bb-128810c8c22e.png)
