### ISSUE TITLE
Delete message

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#431]
The delete message has an extra 'has'.

![screen shot 2016-08-16 at 20 41 22](https://cloud.githubusercontent.com/assets/7042623/17711466/09219d72-63f2-11e6-8de6-50a7e8fe2d05.png)

Original issue posted: https://github.com/ff36/halo-core/issues/96

**Comment by sweety-wo** [comment]
Done.
Changed message for delete messages.

![halo messages](https://cloud.githubusercontent.com/assets/14175105/17725079/66460dc6-6465-11e6-99f4-6db959297ea6.png)
