### ISSUE TITLE
Sector state xeditable

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#432]
For consistency lets make the sector state toggle x-editable:

![screen shot 2016-08-17 at 08 57 39](https://cloud.githubusercontent.com/assets/7042623/17727309/c816bbe8-6458-11e6-9be1-75724555c833.png)

**Comment by sweety-wo** [comment]
Done.
Change sector state change button to X-editable.

![status](https://cloud.githubusercontent.com/assets/14175105/17829254/c4bb74fa-66c6-11e6-8290-aa686e4d909d.png)
![status_change](https://cloud.githubusercontent.com/assets/14175105/17829255/c9732024-66c6-11e6-856e-96e0fc897579.png)
