### ISSUE TITLE
Incident label possiton

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#433]
Lets move the incident 'Cause', 'Remedy' and 'Impact' labels over to the right:

![screen shot 2016-08-17 at 12 23 26](https://cloud.githubusercontent.com/assets/7042623/17733798/a2e22d10-6478-11e6-874e-cd7448ab6f6f.png)

**Comment by sweety-wo** [comment]
Done.
Incident label position shifted to right.
![label shifted to right](https://cloud.githubusercontent.com/assets/14175105/17829449/eabd17e8-66cc-11e6-8d2e-d6a774131013.png)
