### ISSUE TITLE
Message view more not working

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#436]
The message view more button does not work at the moment.

![screen shot 2016-08-20 at 17 29 51](https://cloud.githubusercontent.com/assets/7042623/17836456/ae51e226-6793-11e6-82ef-d9014ac13473.png)

**Comment by sweety-wo** [comment]
Done.
![message view button](https://cloud.githubusercontent.com/assets/14175105/17843958/bf2a3db4-6851-11e6-8d8d-9ee137ad414d.gif)
