### ISSUE TITLE
90% Zoom

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#456]
The system seems to fit much better if I zoom the application to 90% in the browser. Obviously we don't actually want to zoom the application or browser so I suggest we modify the CSS to make everything 10% smaller.

**Comment by sweety-wo** [comment]
For 90% zoom, I have to change all the inspinia css style (element height/width, padding ), bootstrap css style and font size to set as 90% resolution as there is no option available to set zoom in css. Also one more thing, We are using inspinia theme. If we changed all element size and font-style as per 90% then In future we can't update the inspinia theme.

**Comment by tarkal** [comment]
Ok ignore this issue. It's not worth it.

Tarka L'Herpiniere

On Tue, Sep 20, 2016 at 06:46 Sweety WO

<
mailto:Sweety WO <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

For 90% zoom, I have to change all the inspinia css style (element height/width, padding ), bootstrap css style and font size to set as 90% resolution as there is no option available to set zoom in css. Also one more thing, We are using inspinia theme. If we changed all element size and font-style as per 90% then In future we can't update the inspinia theme.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/ff36/halo-gui/issues/456#issuecomment-248200401
, or
