### ISSUE TITLE
Nodes Details Page

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#457]
The node details page is still using the old edit style. It should be updated to be like the rest of the application with x-edit.

![screen shot 2016-09-05 at 16 38 26](https://cloud.githubusercontent.com/assets/7042623/18251086/56d45876-7387-11e6-8e53-5078cac28614.png)

**Comment by sweety-wo** [comment]
Done
![node detail xeditable](https://cloud.githubusercontent.com/assets/14175105/18672032/03e55ae6-7f64-11e6-99d4-130d8cbeebde.gif)
