### ISSUE TITLE
Incident Summary Resolutions

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#462]
For performance reasons I have modified the incident summary endpoint and added a new default resolution.

MONTH -> Max: 12 months (new default)
DAY -> Max 32 days
HOUR -> Max 24 hours
MIN -> Max 60 mins

The original default was to allow 365 days. We just need to add the new higher level heat map as the monthly view with 12 month blocks. The user can then select the month and see the 31 days etc.

**Comment by tarkal** [comment]
For the Month view can we have the label format as the full month name followed by the year. i.e. January 2016, February 2016 etc.

For the Day view can we have the label format as the full day name followed by the date followed by `st`, `nd`, `rd` or `th`. i.e. Monday 1st, Tuesday 2nd etc.

For the Hour view can we have the label format as the full 24 hour clock. i.e. 01:00, 02:00 etc.

For the Hour view can we have the label format as the full 24 hour clock time. i.e. 01:01, 01:02 etc.

**Comment by sweety-wo** [comment]
For Month view: January 2016, February 2016 etc... it is too long to display 
So, I have display it as Jan-16, Feb-16

Also, For Day view i.e. Monday 1st, Tuesday 2nd etc... it is too long to display 
So, I have display it as Mon-01, Tue-02

**Is it ok?**

For the Hour view can we have the label format as the full 24 hour clock. i.e. 01:00, 02:00 etc.

For the Hour view can we have the label format as the full 24 hour clock time. i.e. 01:01, 01:02 etc.

![cal-map](https://cloud.githubusercontent.com/assets/14175105/18410430/964a2cae-7780-11e6-8d0a-50f182a81b52.gif)

**Comment by tarkal** [comment]
Great Job
